### ISSUE TITLE
why static function `parse` cann't find in visual studio 2019

### ISSUE THREAD

**Issue by xmh0511** [nlohmann/json#1894] opened 2020-01-09 05:14 UTC
![issues](https://user-images.githubusercontent.com/17973891/72039905-bab9f180-32e1-11ea-8395-ddcf243d8d10.png)
such as the image shows,the complier cann't find the static method `parse` in the code tips,but it can be complied

**Comment by nlohmann** [comment] 2020-01-09 09:19
Duplicate of #1731.

**Closed by nlohmann** 2020-01-09 09:19 UTC
Labels: kind: question
