### ISSUE TITLE
msgpack unit test failures on ppc64 arch

### ISSUE THREAD

**Issue by dkopecek** [nlohmann/json#524] opened 2017-03-19 19:27 UTC
Hi, I was trying to build[1] the newest release on multiple architectures (Fedora build architectures). There seems to be some msgpack related unit test failure on ppc64. See the attached build log:

[json-ppc64-build.log.txt](https://github.com/nlohmann/json/files/853472/json-ppc64-build.log.txt)

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=18476755

**Comment by nlohmann** [comment] 2017-03-19 21:06
Thanks for the report. Could this be an endianess issue?

**Comment by dkopecek** [comment] 2017-03-20 09:50
Yeah, that would be my guess too. Consider:

```
src/unit-msgpack.cpp:210: FAILED:
  CHECK( json::from_msgpack(result) == j )
with expansion:
  1 == 256
```

which looks like `0x0001 == 0x0100`

**Comment by dkopecek** [comment] 2017-03-20 09:51
ppc64 is big endian

**Comment by user1095108** [comment] 2017-03-31 07:33
if you decide to do the swaps don't forget about bit_cast<>().

**Comment by nlohmann** [comment] 2017-03-31 23:08
I currently do not have the means to test this. Is there a way to have a big endian system with Vagrant?

**Comment by user1095108** [comment] 2017-04-01 11:09
Apparently the users, test this for you, you don't need to test yourself.
Otherwise, try qemu, install a big endian distro and start testing.

2017-04-01 1:08 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-03 20:31
In the end, I need a test setup to at least verify a fix.

I could get qemu to work, but I failed to get a recent Linux with a recent compiler to work, let alone properly integrate it into my network. Hints greatly appreciated!

**Comment by user1095108** [comment] 2017-04-03 22:51
Its very involved, I don't even remember how I did it myself, but I managed
at last. You should use Debian and follow some online tuts.

**Comment by nlohmann** [comment] 2017-04-05 04:57
Hey @dkopecek, could you please try https://github.com/nlohmann/json/blob/feature/manual_lexer/src/json.hpp ? I could not test it with a big-endian system myself.

It is a reimplementation of the binary readers/writers which should respect the byte order.

The main functions are:

```cpp
// from http://stackoverflow.com/a/1001328/266378
static bool little_endianess()
{
    int num = 1;
    return (*reinterpret_cast<char*>(&num) == 1);
}
```

```cpp
// writes a number of type T to vector v
template<typename T>
void write_number(T n)
{
    std::array<uint8_t, sizeof(T)> vec;
    std::memcpy(vec.data(), &n, sizeof(T));

    for (size_t i = 0; i < sizeof(T); ++i)
    {
        // reverse byte order prior to conversion if necessary
        if (is_little_endian)
        {
            v.push_back(vec[sizeof(T) - i - 1]);
        }
        else
        {
            v.push_back(vec[i]);
        }
    }
}
```

```cpp
// reads a number of type T from input
template<typename T>
T get_number()
{
    std::array<uint8_t, sizeof(T)> vec;
    for (size_t i = 0; i < sizeof(T); ++i)
    {
        get();
        check_eof();

        // reverse byte order prior to conversion if necessary
        if (is_little_endian)
        {
            vec[sizeof(T) - i - 1] = static_cast<uint8_t>(current);
        }
        else
        {
            vec[i] = static_cast<uint8_t>(current);
        }
    }

    T result;
    std::memcpy(&result, vec.data(), sizeof(T));
    return result;
}
```

**Comment by user1095108** [comment] 2017-04-05 05:02
This code is inefficient considering that endianess is a compile-time
constant. You could do away with the if.

**Comment by nlohmann** [comment] 2017-04-05 05:37
I could not find such a constant in the standard, and I would like to avoid dozens of `#ifdef`s to cover all compilers. I'm curious whether this fix works in the first place.

**Comment by user1095108** [comment] 2017-04-05 06:50
you can still have a constexpr variable, if you wish, but the real bonus
would be to avoid the if statement.

Example:

#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__ || \
    defined(__BIG_ENDIAN__)
constexpr auto big_endian = true;
#endif

2017-04-05 7:37 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-05 06:51
Is that macro portable?

**Comment by user1095108** [comment] 2017-04-05 06:54
checks boost's endian.hpp and adapt the code there, it's more complete than
my example.

2017-04-05 8:51 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-05 06:55
This was exactly what I wanted to avoid.

**Comment by user1095108** [comment] 2017-04-05 06:57
Avoid boost, yes, but you can still learn from their code.

2017-04-05 8:55 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-05 06:58
I wanted to avoid "dozens of `#ifsef`s".

**Comment by dkopecek** [comment] 2017-04-05 07:20
@nlohmann Cannot confirm that the fix works, because there are some compilation errors. See the attached 
[build.log.txt](https://github.com/nlohmann/json/files/895409/build.log.txt).

**Comment by nlohmann** [comment] 2017-04-05 07:22
Sorry, I forgot I also changed the test suite. You need to check out the whole branch.

**Comment by dkopecek** [comment] 2017-04-05 07:42
@nlohmann Unit tests fail on ppc64 and ppc64le:

ppc64le: https://kojipkgs.fedoraproject.org//work/tasks/1585/18791585/build.log
ppc64: https://kojipkgs.fedoraproject.org//work/tasks/1587/18791587/build.log

**Comment by nlohmann** [comment] 2017-04-05 07:46
Thanks for the feedback. I really need a test system with ppc64.

**Comment by dkopecek** [comment] 2017-04-05 07:53
@nlohmann Check out virt-builder:
 https://developer.fedoraproject.org/tools/virt-builder/about.html
 http://manpages.ubuntu.com/manpages/yakkety/man1/virt-builder.1.html

There are templates for Fedora ppc64, ppc64le, armv7, ... etc. (use `virt-builder -l` to list available templates).

**Comment by nlohmann** [comment] 2017-04-05 18:35
This has nothing to do with the actual error, but the build script is odd:

```
+ doxygen doc/Doxyfile
warning: tag INPUT: input source `../src/json.hpp' does not exist
warning: tag INPUT: input source `index.md' does not exist
warning: source examples is not a readable file or directory... skipping.
warning: source images is not a readable file or directory... skipping.
warning: source ../src/json.hpp is not a readable file or directory... skipping.
warning: source index.md is not a readable file or directory... skipping.
sh: dot: command not found
error: Problems running dot: exit code=127, command='dot', arguments='"/builddir/build/BUILD/json-feature-manual_lexer/html/graph_legend.dot" -Tsvg -o "/builddir/build/BUILD/json-feature-manual_lexer/html/graph_legend.svg"'
error: Problem extracting size from SVG file /builddir/build/BUILD/json-feature-manual_lexer/html/graph_legend.svg
error: Style sheet 'css/mylayout.css' specified by HTML_EXTRA_STYLESHEET does not exist!
```

Instead of calling doxygen directly, one should call `make -Cdoc` instead.

**Comment by nlohmann** [comment] 2017-04-08 21:05
I managed to set up a Debian 3.16.39 with powerpc architecture using qemu. With GCC 4.9.2 I could compile all tests. CBOR/MessagePack are still failing, but at least I can now debug myself ;)

**Comment by user1095108** [comment] 2017-04-08 21:13
Are you sure that it is a big-endian distro? Last time I checked I only saw
little endian ones. Maybe you need a MIPS distro?

2017-04-08 23:06 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-08 21:16
It seems so: 
<img width="671" alt="be" src="https://cloud.githubusercontent.com/assets/159488/24832462/5dda151a-1cb1-11e7-9fae-5682912642e7.png">

**Comment by nlohmann** [comment] 2017-04-08 21:23
With the manual_lexer branch, there is only one test failing for CBOR and MessagePack, respectively:

<img width="637" alt="msgpack64" src="https://cloud.githubusercontent.com/assets/159488/24832520/42bbd01a-1cb2-11e7-87ab-d5374193e74b.png">

**Comment by nlohmann** [comment] 2017-04-08 22:05
With the last commit (https://github.com/nlohmann/json/commit/6f99d5b2e978ee6ef448fe39a426ba12c101f8f9) all tests succeed.

**Comment by nlohmann** [comment] 2017-04-10 19:13
@dkopecek Could you please check whether the fix works for you?

**Comment by user1095108** [comment] 2017-04-10 19:31
Hey, don't forget MIPS, now that you're at it.

2017-04-10 21:13 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by dkopecek** [comment] 2017-04-10 19:31
@nlohmann Oops, sorry, I was planning to but totally forgot :-) I'll check it out tomorrow (CEST timezone) and let you know.

**Comment by nlohmann** [comment] 2017-04-10 19:37
What's wrong with MIPS?

**Comment by user1095108** [comment] 2017-04-10 19:38
It's big-endian, just like PPC.

2017-04-10 21:37 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-10 19:39
Yes, and I proposed a fix for big endianess. I assume it also works for MIPS, but I already had troubles getting PPC to work.

**Comment by user1095108** [comment] 2017-04-10 19:41
Try it if you have time, on MIPS.

2017-04-10 21:40 GMT+02:00 Niels Lohmann <notifications@github.com>:

**Comment by nlohmann** [comment] 2017-04-10 19:42
Sorry, i don't, and would appreciate help on this issue.

**Comment by dkopecek** [comment] 2017-04-11 12:29
@nlohmann results:

x86_64: ok
ppc64le: ok
aarch64: ok
ppc64: **FAIL**
i686: ok
armv7hl: ok

but this time it's a different fail. see the attached [ppc64-build.log.txt](https://github.com/nlohmann/json/files/913153/ppc64-build.log.txt)

**Comment by nlohmann** [comment] 2017-04-11 12:45
Thanks for reporting. Could you rerun the tests with

```
make json_unit
test/json_unit "*"
```

This runs all tests and does not abort after the first failure.

**Comment by dkopecek** [comment] 2017-04-11 15:25
Interesting. With that testing procedure, the tests don't fail on ppc64 and do fail on armv7hl. So there seems to be something non-deterministic in the tests.

[armv7hl-build.log.2.txt](https://github.com/nlohmann/json/files/913735/armv7hl-build.log.2.txt)
[ppc64-build.log.2.txt](https://github.com/nlohmann/json/files/913736/ppc64-build.log.2.txt)

**Comment by nlohmann** [comment] 2017-04-11 17:04
That is indeed strange. The tests should be (of course) deterministic, but since the ARM error is a SIGSEGV, maybe just a different call could have triggered it. Without debugging, I cannot tell much about the issue...

Could I ask you to try the following?

```
make test-conversions -Ctest
test/test-conversions -s
```

This should give us more information on when the test crashes.

**Comment by nlohmann** [comment] 2017-04-11 17:04
(On the bright side, it seems as if the fix for the endianess issue seems to work)

**Comment by dkopecek** [comment] 2017-04-12 08:38
> Could I ask you to try the following?
> 
> make test-conversions -Ctest
> test/test-conversions -s

Doesn't fail at all. Tried several times.

**Comment by nlohmann** [comment] 2017-04-12 08:57
Strange... Could you try to execute the tests with Valgrind?

**Comment by dkopecek** [comment] 2017-04-12 10:12
Here are the logs. x86_64 is ok but I've attached it anyway.

[armv7hl-build.3.log.txt](https://github.com/nlohmann/json/files/916159/armv7hl-build.3.log.txt)
[ppc64-build.3.log.txt](https://github.com/nlohmann/json/files/916160/ppc64-build.3.log.txt)
[x86_64-build.3.log.txt](https://github.com/nlohmann/json/files/916161/x86_64-build.3.log.txt)

**Comment by nlohmann** [comment] 2017-06-11 16:36
I think I need to close this issue. I cannot reproduce the problem, and I can do little with the provided logs.

**Closed** 2017-07-09 14:57 UTC
Labels: aspect: binary formats, kind: bug, solution: proposed fix, state: help needed
