### ISSUE TITLE
find is error

### ISSUE THREAD

**Issue by lonerwolf** [nlohmann/json#32] opened 2015-01-20 02:55 UTC
json o;
o["foo"] = 23;
o["bar"] = false;
o["baz"] = 3.141;

// find an entry
if (o.find("foo") != o.end()) {
  // there is an entry with key "foo"
}

in my example

key:"Heart_COL"
type:"HEX"
val:"DF01140234340000"

auto it = jsonData.find("type");
std::cout << *it << '\n';
the printf data is "Heart_COL"

**Comment by lonerwolf** [comment] 2015-01-20 02:56
@nlohmann

**Comment by nlohmann** [comment] 2015-01-20 09:08
I'll check tonight.

**Comment by nlohmann** [comment] 2015-01-20 16:35
I do not really understand your problem. I tried the following code:

```cpp
json jsonData = {{"Heart_COL", "DF01140234340000"}};
auto it = jsonData.find("type");
//std::cout << *it << '\n'; will throw, because it == json.end()
it = jsonData.find("Heart_COL");
std::cout << *it << '\n'; // prints "DF01140234340000"
std::cout << it.key() << '\n'; // prints Heart_COL
std::cout << it.value() << '\n'; // prints "DF01140234340000"
std::cout << it->get<std::string>() << '\n'; // prints DF01140234340000
```

What did you try to achieve in your code? What went wrong?

**Comment by nlohmann** [comment] 2015-01-21 16:46
@lonerwolf, could you please comment?

**Comment by nlohmann** [comment] 2015-01-24 19:43
I close this issue until the problem is clear.

**Closed by nlohmann** 2015-01-24 19:43 UTC
Labels: invalid
