### ISSUE TITLE
Failed to run tests due to missing test data on builders without Internet access

### ISSUE THREAD

**Issue by xvitaly** [nlohmann/json#2190] opened 2020-06-15 13:17 UTC
#### What is the issue you have?

Failed to run tests due to missing test data on builders without Internet access.

#### Please describe the steps to reproduce the issue.

1. Run build and tests on system without Internet access.
2.
3.

#### What is the expected behavior?

It should be able to run tests offline without Internet access. Most of GNU/Linux distributions strictly forbid Internet access during official builds.

#### And what is the actual behavior instead?

All tests are failed.

#### Which compiler and operating system are you using?

- Compiler: gcc 10.1.1
- Operating system: Fedora 32

#### Which version of the library did you use?

- [x] latest release version 3.7.3
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment] 2020-06-15 13:19
This is a duplicate of #2189.

**Closed** 2020-06-15 13:19 UTC
Labels: kind: enhancement/improvement, solution: duplicate

**Comment by nlohmann** [comment] 2020-06-21 06:44
Fixed with #2202.
