### ISSUE TITLE
Parser issues

### ISSUE THREAD

**Issue by berkus** [nlohmann/json#509] opened 2017-03-16 17:14 UTC
on a following json `{"body": "text\v"}`
it gives
`parse error at 10: parse error - unexpected '"'`

dropbox/json11 gives:

`unescaped (11) in string`

which is correct (this is an unescaped vertical tab, disallowed by JSON std)

**Comment by nlohmann** [comment] 2017-03-16 17:30
The scanner recognizes the malformed string and returns a `parse_error` token. The problem is the implementation of the `unexpect` function. I wanted to be clever and avoid a `unexpected parse error` output, so I output the text of the last token which in this case is only the opening `"`. I have to look into this.

**Comment by nlohmann** [comment] 2017-03-28 21:50
With the overworked scanner in branch [manual_lexer](https://github.com/nlohmann/json/tree/feature/manual_lexer), the error message for the above code is

```
[json.exception.parse_error.101] parse error at 16: syntax error - invalid string: forbidden character after backspace; last read '"text\v'
```

**Comment by nlohmann** [comment] 2017-04-08 10:38
The example in #551 shows that the diagnosis information got better. However, the output could be improved: `last read '"\303?'` does not help too much here.

**Comment by nlohmann** [comment] 2017-05-07 12:25
The new scanner (merged yesterday) now provides the diagnosis information described in https://github.com/nlohmann/json/issues/509#issuecomment-289915749.

**Comment by berkus** [comment] 2017-05-12 20:13
After *backspace*?

**Comment by nlohmann** [comment] 2017-05-13 17:57
Ooops. Fixed this.

**Closed by nlohmann** 2017-05-13 17:57 UTC
Labels: confirmed, kind: bug
