### ISSUE TITLE
Can't throw exception when starting file is a number

### ISSUE THREAD

**Issue by h3x4n1um** [nlohmann/json#1649] opened 2019-06-23 15:34 UTC
- What is the issue you have?

When parsing binary file, if several first bytes of file is number, the json parser not throw an exception

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

The below example show that it recognize `fake_undetected.json` file is a json file
```cpp
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>

#include "json.hpp"

int main(){
    std::ifstream input;
    std::ofstream output;
    nlohmann::json js;
    int test = 2019;

    //create real json
    output.open("real.json");
    js["Hello"] = "Hi";
    js["Year"] = test;
    output << std::setw(4) << js;
    output.close();

    //create detected fake json file
    output.open("fake_detected.json", std::ofstream::binary);
    output.write(reinterpret_cast <const char*> (&test), sizeof test);
    output.close();

    //create undetected fake json file
    output.open("fake_undetected.json", std::ofstream::binary);
    output << test;
    output.write(reinterpret_cast <const char*> (&test), sizeof test);
    output.close();

    //verify json
    std::filesystem::path p = std::filesystem::current_path();
    for (auto &file : std::filesystem::recursive_directory_iterator(p)){
        if (std::filesystem::is_regular_file(file.path())){
            input.open(file.path());
            try{
                input >> js;
                std::cout << file.path() << " is a json" << std::endl;
            }
            catch(nlohmann::json::exception &e){
                std::cerr << file.path() << " is not a json" << std::endl;
            }
            input.close();
        }
    }
    return 0;
}
```

- What is the expected behavior?

It should throw `nlohmann::json::exception` when parse `fake_undetected.json`

- And what is the actual behavior instead?

Opposite above

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

I use GCC 9.0 (MSYS2 with MinGW-w64 package) and compile using
```
g++ -lstdc++fs -std=c++17 -c test.cpp -o test.o
```

- Did you use a released version of the library or the version from the `develop` branch?

I use released version 3.6.1 of the library

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

<a href="https://i.kym-cdn.com/entries/icons/original/000/029/847/cover4.jpg" target="_blank">Hello, world!</a>

**Comment by nlohmann** [comment] 2019-06-24 05:26
The issue is that parsing via `input >> json` is not required to read the stream until the last character: if the prefix is a JSON value, it is returned and the stream is left at the first character after the parsed value. This allows for incremental parsing from a stream.

For your case, try using the static function `json::parse`. It takes the input as parameter and will throw if the input is not completely read.

Here is an example:

```cpp
#include "json.hpp"
#include <iostream>
#include <sstream>

using json = nlohmann::json;

int main()
{
    // works and prints "123"
    {
        std::stringstream ss;
        ss << "123ab" << std::endl;
        
        json j;
        ss >> j;
        
        std::cout << j << std::endl;
    }
    
    // throws [json.exception.parse_error.101] parse error at line 1, column 4: syntax error while parsing value - invalid literal; last read: '123a'; expected end of input
    {
        std::stringstream ss;
        ss << "123ab" << std::endl;

        json j = json::parse(ss);
    }
}
```

**Comment by nlohmann** [comment] 2019-06-29 12:48
@h3x4n1um Do you need further assistance?

**Comment by h3x4n1um** [comment] 2019-06-29 16:24
> @h3x4n1um Do you need further assistance?

Thankyou, that's very kind of you but I think using `json::parse` as a workaround is fine for me until the problem is fixed

**Comment by nlohmann** [comment] 2019-06-30 06:08
For `operator>>` I cannot pass a parameter to control whether trailing characters should be treated like an error. For `parse` I could add another parameter, but this is not yet planned. So at least for the near future, there will be no fix for this.

**Closed by nlohmann** 2019-06-30 06:08 UTC
Labels: kind: bug, solution: proposed fix
