### ISSUE TITLE
convert json value to std::string???

### ISSUE THREAD

**Issue by Mamlesh** [nlohmann/json#1061] opened 2018-04-19 11:09 UTC
how to convert json value to string ..

**Comment by Mamlesh** [comment] 2018-04-19 11:52
thanks for replay sir....
i need to convert the json value ....example

json jk; json jsd;
jk.pushback(jsd);

string str=jk;

wnat to use 'jk' value as string....

**Comment by whackashoe** [comment] 2018-04-19 12:01
From README

```
You can also get a string representation of a JSON value (serialize):

// explicit conversion to string
std::string s = j.dump();    // {\"happy\":true,\"pi\":3.141}

// serialization with pretty printing
// pass in the amount of spaces to indent
std::cout << j.dump(4) << std::endl;
// {
//     "happy": true,
//     "pi": 3.141
// }
```

**Comment by nlohmann** [comment] 2018-04-23 17:42
Can I close this issue?

**Comment by AOrazaev** [comment] 2018-04-27 00:26
@nlohmann Probably not, looks like case with operator= messed up:

```
  json fail = R"({"foo": "bar"})"_json;
  // std::string barExpected;`
  // barExpected = fail["foo"]; // fails`
  std::string barExpected = std::string(fail["foo"]); //works
```

**Comment by nlohmann** [comment] 2018-04-27 05:11
@AOrazaev I cannot reproduce the error. Which compiler are you using? What is the error message?

**Comment by rue-ryuzaki** [comment] 2018-04-27 19:57
Maybe like this?

> std::string value = parser["value"].get<std::string>();

**Comment by AOrazaev** [comment] 2018-04-27 23:06
@rue-ryuzaki Yep, I've worked around this like you said.

@nlohmann I compiled example from VS2017.
For some reason, when I'm compiling from developer console on small example using cl.exe I'm not getting this error, but from VS2017 actually I'm getting next:
```
Severity	Code	Description	Project	File	Line	Suppression State	Detail Description
Error (active)	E0350	more than one operator "=" matches these operands:	check_json	check_json.cpp	13		            function "std::basic_string<_Elem, _Traits, _Alloc>::operator=(std::basic_string<_Elem, _Traits, _Alloc> &&_Right) [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
            function "std::basic_string<_Elem, _Traits, _Alloc>::operator=(std::initializer_list<_Elem> _Ilist) [with _Elem=char, _Traits=std::char_traits<char>, _Alloc=std::allocator<char>]"
            operand types are: std::string = const nlohmann::basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann::adl_serializer>
```

Code I used to reproduce:
```
#include "json.hpp"
#include "stdafx.h" // only if using VS
#include <iostream>
#include <string>

using nlohmann::json;

struct JsonWrapper {
    std::string _foo;
public:
    JsonWrapper(const json& obj)
    {
        _foo = obj["foo"];
    }

    void log() {
        std::cout << "Foo: " << _foo << std::endl;
    }
};

int main() {
    json obj = R"({"foo": "bar"})"_json;
    JsonWrapper wrap{ obj };
    wrap.log();
    return 0;
}

```

**Comment by AOrazaev** [comment] 2018-04-27 23:09
And if insead of:
```
    JsonWrapper(const json& obj)
    {
        _foo = obj["foo"];
    }
```


Use:

```
    JsonWrapper(const json& obj)
        : _foo(obj["foo"])
    {    }
```


It will fail in developer cmd with cl.exe too. complaining about
```
error C2668: 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>::basic_string': ambiguous call to overloaded function
```

**Comment by nlohmann** [comment] 2018-04-29 15:37
@AOrazaev Your issue seems not related to the original comment.

**Comment by nlohmann** [comment] 2018-04-29 15:38
@AOrazaev For https://github.com/nlohmann/json/issues/1061#issuecomment-385115936, using 

```cpp
JsonWrapper(const json& obj)
    : _foo(obj["foo"].get<std::string>())
{}
```

works though.

**Comment by AOrazaev** [comment] 2018-04-30 04:09
I mean, probably topic starter tried his example in VS and hit issue I described before.

I personally worked around everything with get<std::string>, but bug is still there.

**Comment by nlohmann** [comment] 2018-05-04 15:26
@Mamlesh Can I close this issue?

**Closed** 2018-05-11 16:12 UTC
Labels: solution: proposed fix
