### ISSUE TITLE
can two json objects be concatenated?

### ISSUE THREAD

**Issue by CheyenneForbes** [nlohmann/json#1019] opened 2018-03-20 18:27 UTC
for example:

```
json j1 = {
 {obj1, value1},
 {obj2, value2}
};
json j2 = {
 {obj3, value3},
 {obj4, value4}
};

json j3 = j1 + j2;
```

**Comment by nlohmann** [comment] 2018-03-20 18:31
Duplicate of #428, implemented with the [`update`](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a1cfa9ae5e7c2434cab4cfe69bffffe11.html#a1cfa9ae5e7c2434cab4cfe69bffffe11) function.

**Comment by gregmarr** [comment] 2018-03-20 18:31
https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L14797-L14816

    json j3 = j1;
    j3.update(j2);

**Closed** 2018-03-27 06:15 UTC
Labels: kind: question, solution: duplicate, solution: proposed fix

**Comment by p-i-** [comment] 2019-01-31 08:18
Fantastic to find `update`.
Is there any particular reason not to overload `+` and `+=`?
That's the first thing I tried: `j2 += j1`
I think that would be a really neat syntax.

**Comment by jaredgrubb** [comment] 2019-01-31 16:34
There's not a lot to gain by adding *another* way to do this as there are only a few characters difference between the two. I personally like the Python mantra: "There should be one -- and preferably only one -- obvious way to do it.". C++ doesn't always live up to this, but it's a nice rule in general.

But, I'd also expect addition operations to have familiar properties like commutivity (eg, "j1+j2" and "j2+j1" should give the same result, but for JSON they wouldn't!). Sure, std::string has a non-commutative "+" but that doesn't mean we should give up on that goal.

**Comment by DolphinDream** [comment] 2022-09-02 16:45
Does this update method work with merging recursively?  
`j1 = { “attributes”: { “background-color”: “red”}, “prop1”: 2 }` 
`j2 = { “attributes”: { “text-color”: “blue”}, “prop2”: 3 }`

Merging j1 and j2 (concatenating, updating) I would expect to get:

`{ “attributes”: { “background-color”: “red”, “text-color”: “blue”}, “prop1”: 2, “prop2”: 3 } `

I’m not sure if any changes to merge occurred since 3.3.0 .. but in this older version when merging only the top level properties are concatenated.. namely, if there is a duplicate to be merged (albeit with different subtree values) the previous property is being replaced by the duplicate property in the other j object. Essentially merging j1.update(j2) creates this:

`{ “attributes”: { "text-color”: “blue”}, “prop1”: 2, “prop2”: 3 } `

which removes the previous attributes values.

```
  fifo_json j1;
  j1["attributes"]["background-color"] = "red";
  j1["prop1"] = 2;
  cout << "j1 = " << endl;
  cout << j1.dump(2) << endl;

  fifo_json j2;
  j2["attributes"]["text-color"] = "blue";
  j2["prop2"] = 3;
  cout << "j2 = " << endl;
  cout << j2.dump(2) << endl;

  // concatenate
  j1.update(j2);
  cout << "j1+j2 = " << endl;
  cout << j1.dump(2) << endl;
```

gives the output:

```
j1 = 
{
  "attributes": {
    "background-color": "red"
  },
  "prop1": 2
}
j2 = 
{
  "attributes": {
    "text-color": "blue"
  },
  "prop2": 3
}
j1+j2 = 
{
  "attributes": {
    "text-color": "blue"
  },
  "prop1": 2,
  "prop2": 3
}
```

**Comment by gregmarr** [comment] 2022-09-02 16:47
@DolphinDream There is now a recursive parameter to the `update` function.  https://github.com/nlohmann/json/blob/master/docs/mkdocs/docs/api/basic_json/update.md

**Comment by DolphinDream** [comment] 2022-09-02 16:50
> @DolphinDream There is now a recursive parameter to the `update` function. https://github.com/nlohmann/json/blob/master/docs/mkdocs/docs/api/basic_json/update.md

Yeah.. i just noticed "Added merge_objects parameter in 3.10.4” .. which explains my 3.3.0 issue :)

**Comment by nlohmann** [comment] 2022-09-02 16:50
See https://json.nlohmann.me/api/basic_json/update/
