### ISSUE TITLE
Unnecessary test data file in the release

### ISSUE THREAD

**Issue by aaquant** [nlohmann/json#1790] opened 2019-10-14 14:30 UTC
The total repo exceeds 200MB in size. 
An ordinary user of this library doesn't need those data or test output data file. 
Please do not include those files in the release branch, some examples are:

test/data
test/reports
benchmark/data

Those files are needed by developers of this project.  

Without those files, the size of the repo can be reduced to 2.6MB.

**Comment by gregmarr** [comment] 2019-10-14 20:30
Duplicate of #96.

**Comment by jeffreyscottgraham** [comment] 2019-11-14 00:13
I for one was waiting for this improvement. I don't understand how it is stale, since the change must happen by the repo owner? Or are you wanting a PR ?

**Comment by nlohmann** [comment] 2019-11-14 08:50
Sorry, I did not find the time to work on this.

**Closed** 2020-05-04 18:58 UTC
Labels: kind: enhancement/improvement, release item: :hammer: further change, solution: proposed fix
