### ISSUE TITLE
Iterate over leafs of a JSON data structure: enrich the JSON pointer API

### ISSUE THREAD

**Issue by SylvainCorlay** [nlohmann/json#1054] opened 2018-04-16 00:20 UTC
**Enriching the  `json_pointer` API**

I noticed that the `json_pointer` class stored a `std::vector<std::string>` internally.

With private inheritance instead of composition, and a bunch of `using` statements to forward the API, you would enable a JSON pointer with a richer API, such as

 - initialize with initializer lists.
 - push / pop -pack for new values in the paths.

**The use case**

My use-case is that I would like to iterate over all the leafs (number, boolean, null, strings) of a nested JSON data structure..

In order to do so, I would keep a vector of strings for the current position to which new elements are pushed back when meeting an array or object, and popped when leaving a level.

If this "key" is a JSON pointer, it could be used for access later, while right now, I would need to compose a string from it and pass it to the constructor of `json_pointer`, which is not very efficient.

**Comment by nlohmann** [comment] 2018-04-16 03:06
Related: #837

**Comment by nlohmann** [comment] 2018-04-16 06:52
Could you please provide more information on the described use case? Is the use of JSON Pointers fixed or would a different solution also be helpful? On iteration of nested elements, this may be helpful: https://stackoverflow.com/questions/45934851/c-nlohmann-json-how-to-iterate-find-a-nested-object/46630394#46630394

**Comment by nlohmann** [comment] 2018-04-17 05:53
I am hesitant on adding an `operator[]` with a string access. This is exactly what JSON Pointers are for - including a well-defined syntax and semantics. If further manipulation of the path is required, then this would be possible with #837.

I would be happy for further discussion on this!

**Comment by SylvainCorlay** [comment] 2018-04-17 06:31
> I am hesitant on adding an operator[] with a string access. This is exactly what JSON Pointers are for - including a well-defined syntax and semantics. If further manipulation of the path is required, then this would be possible with #837.

Hum, this is not what I suggested! I merely suggested to give JSON pointer a general std::vector API.

**Comment by nlohmann** [comment] 2018-04-17 06:32
So this issue could be seen as a duplicate of #837?

**Comment by SylvainCorlay** [comment] 2018-04-17 06:47
Maybe, although the idea of a `push_back` with a slash-separated string is weird, since the STL has APIs to manipulate sequences.

Something like

```
jp.insert(jp.end(), {
    "few",
    "more",
    "items"
});
```

is more natural than 

```
jp.push_back("few/more/items");
```

also, having a special API based on `operator/=` and such would make it impossible to use generic algorithms on json_pointers.

**Comment by nlohmann** [comment] 2018-04-17 06:48
Ok, I reopened #837. Let's join the discussion there.

**Comment by nlohmann** [comment] 2018-04-17 06:49
Duplicate of #837.

**Closed by nlohmann** 2018-04-17 06:49 UTC
Labels: solution: duplicate

**Comment by SylvainCorlay** [comment] 2018-04-17 06:52
Thanks
