### ISSUE TITLE
Please fix failing tests

### ISSUE THREAD

**Issue by tellypresence** [nlohmann/json#3923] opened 2023-01-13 23:22 UTC
### Description

Most recent passing test was 2 Oct 2022
![nlohmann_json_failing_tests](https://user-images.githubusercontent.com/26958898/212436397-7fde786c-d4e7-4736-a484-5849328712ed.png)

### Reproduction steps

N/A: just open "Commits" page on github and look for red "X"'s

### Expected vs. actual results

N/A: just open "Commits" page on github and look for red "X"'s

### Compiler and operating system

N/A: just open "Commits" page on github and look for red "X"'s

### Library version

N/A: just open "Commits" page on github and look for red "X"'s

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment] 2023-01-14 15:04
Duplicate of #3890.

**Closed as not planned by nlohmann** 2023-01-14 15:04 UTC
Labels: kind: bug, solution: duplicate
