### ISSUE TITLE
Compiling 3.6.0 with GCC > 7, array vs std::array #590 is back

### ISSUE THREAD

**Issue by niklas88** [nlohmann/json#1530] opened 2019-03-20 11:38 UTC
As a user I can't reopen an issue and I fear commenting on it might get lost.
Anyway as of the 3.6.0 release #590 is back from the dead.
My guess is that the fix of adding parenthesis was removed by some code formatter
here is the problematic line in the current version:

https://github.com/nlohmann/json/blob/release/3.6.0/include/nlohmann/json.hpp#L5731

Also this problem still appears with GCC 8.2.1

**Comment by nlohmann** [comment] 2019-03-20 11:42
Thanks for reporting! I am using GCC 7 and 8 in the CI, but did not catch this issue. Strange... Anyway, could you please check whether the issue is fixed in c790b9f8c04e287dd2022f3f28abeffbc2a02706?

**Comment by niklas88** [comment] 2019-03-20 11:42
Closing as the original issue has been reopened

**Comment by nlohmann** [comment] 2019-03-20 11:43
Let's have the regression here.

**Comment by niklas88** [comment] 2019-03-20 11:44
Ah, I'm too fast. Yes that patch should fix it as locally adding the parenthesis does

**Comment by nlohmann** [comment] 2019-03-20 12:00
* * *

### 🔖 Release item

This issue/PR will be part of the next release of the library. This template helps preparing the release notes.

#### Type

- [ ] ✨ New Feature
- [x] 🐛 Bug Fix
- [ ] ⚡️ Improvement
- [ ] 🔨 Further Change
- [ ] 🔥 Deprecated function

#### Description

- Fixed regression of #590 which could lead to compilation errors with GCC 7 and GCC 8. #1530

* * *

**Comment by niklas88** [comment] 2019-03-20 13:30
@nlohmann I just found out that the same code in the `single_include/nlohmann/json.hpp` still has this problem

**Comment by nlohmann** [comment] 2019-03-20 13:30
I changed both files. What is the exact error message?

**Comment by niklas88** [comment] 2019-03-20 13:32
The parenthesis are wrong it needs to be ` return (*lhs.m_value.array) < (*rhs.m_value.array);` I guess I didn't look close enough in the commit

**Comment by nlohmann** [comment] 2019-03-20 13:41
Could you try again with b33093d6104827f07ad6e7ffcc2b89f4f9256f2d?

**Comment by niklas88** [comment] 2019-03-20 14:18
I've tested with the single include from https://github.com/nlohmann/json/commit/b33093d6104827f07ad6e7ffcc2b89f4f9256f2d and can confirm that it now compiles and works. I'm sorry for getting it wrong last time I think I just assumed that it was the same parenthesis as in https://github.com/nlohmann/json/commit/1a9d76679a3f41a038a89742fba29d81ee24ce82 where I looked up the fix.

**Comment by nlohmann** [comment] 2019-03-20 14:24
No worries - it was me who got this regression slipped in. Thanks for your help!

**Closed by nlohmann** 2019-03-20 14:24 UTC
Labels: kind: bug, release item: :bug: bug fix, solution: proposed fix
