### ISSUE TITLE
JSON Comments (JSON 5)

### ISSUE THREAD

**Issue by robiwano** [nlohmann/json#2090] opened 2020-05-07 06:30 UTC
- Describe the feature in as much detail as possible.
Simple, it would be great if this project would support JSON 5 (https://json5.org/), which has both comment support and doesn't choke on trailing commas.

**Comment by nlohmann** [comment] 2020-05-07 06:46
Duplicate of https://github.com/nlohmann/json/issues/348. Please see also https://github.com/nlohmann/json#comments-in-json.

**Closed** 2020-05-07 07:58 UTC
Labels: kind: enhancement/improvement, solution: duplicate, solution: wontfix
