### ISSUE TITLE
Latest version 3.9.1 uses throw instead of JSON_THROW in the amalgamated json.hpp file

### ISSUE THREAD

**Issue by xykivo** [nlohmann/json#2934] opened 2021-08-14 23:41 UTC
#### What is the issue you have?

In the 3.9.1 release, the amalgamated header (json.hpp), contains 2 throw statements
- Line 16454
- Line 16467

This causes compilation with the -fno-exceptions flag to fail.
Replacing these throw calls with JSON_THROW solves the issue.

I tried to fix the issue and create a pull request. However I couldn't find where these 2 lines are generated in the source code.

#### Please describe the steps to reproduce the issue.

1. Include json.hpp in a C++ source file (simple main that includes the header, and create a json instance is enough)
2. Compile the source file (using gcc or clang) with -fno-exceptions
3 Compilation fails because of the throw statements
4. Replace throw statements with JSON_THROW
5. Compilation passes

#### Can you provide a small but working code example?

See above

#### What is the expected behavior?

Compiling with -fno-exceptions should pass

#### And what is the actual behavior instead?

Compilation with -fno-exceptions fails

#### Which compiler and operating system are you using?

- Operating system: Ubuntu 20.04
- Compiler: clang 10.0.0
- Compiler: gcc 9.3.0

#### Which version of the library did you use?

3.9.1

- [x ] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

Did not check unit tests.

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment] 2021-08-15 05:29
This has been fixed in the develop branch.

**Comment by nlohmann** [comment] 2021-08-15 08:03
Duplicate of #2725.

**Closed by nlohmann** 2021-08-15 08:03 UTC
Labels: kind: bug, solution: proposed fix
