### ISSUE TITLE
MSVC warning C4946 ("reinterpret_cast used between related classes") compiling json.hpp

### ISSUE THREAD

**Issue by Mark-Dunning** [nlohmann/json#1502] opened 2019-03-06 01:54 UTC
- What is the issue you have?

C4946 compiler warnings are generated when compiling json.hpp with MSVC. Note that this is an off-by-default warning but it is quite useful to detect redundant use of reinterpret_cast.

In this case it looks like the warnings are correct and the reinterpret_casts are unnecessary.

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

Just compile json.hpp with C4946 warnings enabled:

    > cl /TP /EHsc /we4946 json.hpp

    Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27027.1 for x86
    Copyright (C) Microsoft Corporation.  All rights reserved.

    json.hpp
    json.hpp(4755): error C4946: reinterpret_cast used between related classes: 'nlohmann::detail::exception' and 'nlohmann::detail::other_error'
    ...

- What is the expected behavior?

No warnings.

- And what is the actual behavior instead?

Warnings are generated.

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Microsoft Visual Studio 2017 15.9.8 on Windows 10 1809.

- Did you use a released version of the library or the version from the `develop` branch?

The 3.5.0 release.

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

n/a

**Comment by nlohmann** [comment] 2019-03-10 06:17
I do not understand the warning, because `other_error` is inheriting from `exception`. Could this be a false positive?

**Comment by gregmarr** [comment] 2019-03-10 23:59
I think it's saying use static_cast instead.

**Comment by Mark-Dunning** [comment] 2019-03-11 00:53
Yes, that's right. The idea is that `reinterpret_cast` is a more 'dangerous' cast than a `static_cast` and should be reserved for cases when you really need it (e.g. casting a pointer to an `intptr_t`). It's also less descriptive of your intentions (not that `static_cast` is particularly great).

From https://en.wikipedia.org/wiki/Static_cast

> The static_cast operator can be used for operations such as: ...
> Converting a pointer of a base class to a pointer of a nonvirtual derived class,

**Comment by nlohmann** [comment] 2019-03-11 06:41
Thanks, good point!

**Comment by nlohmann** [comment] 2019-03-11 14:39
@Mark-Dunning Could you please check if the issue is fixed in the latest develop branch?

**Comment by Mark-Dunning** [comment] 2019-03-11 22:04
Yes, I've just tried the latest 'develop' branch and the warning is no longer raised. Thanks very much!

**Comment by nlohmann** [comment] 2019-03-11 22:05
Thanks for reporting and checking!

**Closed by nlohmann** 2019-03-11 22:05 UTC
Labels: platform: visual studio, release item: :hammer: further change, solution: proposed fix
