### ISSUE TITLE
ambiguous overload for 'push_back' and 'operator+='

### ISSUE THREAD

**Issue by alestrooisma** [nlohmann/json#235] opened 2016-04-19 12:05 UTC
When compiling this very simple program with g++ 4.9.2, I get "ambiguous overload" errors about both the `push_back` and the `operator+=` calls.

```cpp
#include <iostream>
#include "json.hpp"

using json = nlohmann::json;

int main(int argc, char** argv) {
    json data = {{"key", "value"}};
    data.push_back({"key2", "value2"});
    data += {"key3", "value3"};
    return 0;
}
```

See [here](http://pastebin.com/5MwBXULU) for the compiler output (it's rather large)

**Comment by nlohmann** [comment] 2016-04-19 20:47
I confirm the error. With clang 7.3.0 (clang-703.0.29), the error is a bit shorter (but basically the same):

```
issue235.cpp:7:10: error: call to member function 'push_back' is ambiguous
    data.push_back({"key2", "value2"});
    ~~~~~^~~~~~~~~
./../src/json.hpp:4883:10: note: candidate function
    void push_back(basic_json&& val)
         ^
./../src/json.hpp:4919:10: note: candidate function
    void push_back(const basic_json& val)
         ^
./../src/json.hpp:4969:10: note: candidate function
    void push_back(const typename object_t::value_type& val)
         ^
issue235.cpp:8:10: error: use of overloaded operator '+=' is ambiguous (with operand types 'json' (aka 'basic_json<>') and 'void')
    data += {"key3", "value3"};
    ~~~~ ^  ~~~~~~~~~~~~~~~~~~
./../src/json.hpp:4909:15: note: candidate function
    reference operator+=(basic_json&& val)
              ^
./../src/json.hpp:4943:15: note: candidate function
    reference operator+=(const basic_json& val)
              ^
./../src/json.hpp:4993:15: note: candidate function
    reference operator+=(const typename object_t::value_type& val)
              ^
```

**Comment by gregmarr** [comment] 2016-04-19 20:56
I wonder if having an emplace_back that chained to the vector version would be less ambiguous.

**Comment by nlohmann** [comment] 2016-05-08 16:28
The problem is that `{"key", "value"}` can be both interpreted as `object_t::value_type` or `std::initializer_list<basic_json>`. A solution could be to add an overload `void push_back(std::initializer_list<basic_json>)` and to create and `object_t::value_type` from that initializer list. First tries broke some tests, so I am not sure whether this will work in the end.

**Comment by nlohmann** [comment] 2016-05-08 18:45
Fixed with last commit to develop branch.

**Closed by nlohmann** 2016-05-08 18:45 UTC
Labels: bug, confirmed

**Comment by alestrooisma** [comment] 2016-05-09 10:01
Can confirm that it is fixed. Thanks for the fix and the great library!
