### ISSUE TITLE
json::parse is not a member

### ISSUE THREAD

**Issue by abecko47** [nlohmann/json#1832] opened 2019-11-08 17:11 UTC
- Describe what you want to achieve.
I want deserialize string to json object
- Describe what you tried.
`json j = "{}"_json; //works fine`
![image](https://user-images.githubusercontent.com/10388830/68496633-7a93af80-025b-11ea-8198-13ed6f18c6ae.png)

- Describe which system (OS, compiler) you are using.
Windows 10, visual studio 2019
- Describe which version of the library you are using (release version, develop branch).
nlohmann-json 3.7.0 (x86)

**Comment by nlohmann** [comment] 2019-11-08 17:47
This is a duplicate of #1731.

**Closed by nlohmann** 2019-11-08 17:47 UTC
Labels: kind: question
