### ISSUE TITLE
Unexpected deserialization difference between Mac and Linux

### ISSUE THREAD

**Issue by wbuck** [nlohmann/json#2338] opened 2020-08-04 21:46 UTC
#### What is the issue you have?

<h4>When deserializing the following json from a file on macOS</h4>

    {
        "SaveAllImages": true,
        "SaveOnlyFailedImages": false,
        "RedThreshold": 215,
        "MaxRedThreshold": 255,
        "BlueThreshold": 215,
        "MaxBlueThreshold": 255,
        "BlobFilterArea": true,
        "BlobMinAreaPx": 2000,
        "BlobMaxAreaPx": 6000,
        "BlobMinThreshold": 10,
        "BlobMaxThreshold": 10000,
        "BlobFilterCircularity": true,
        "BlobMinCircularity": 0.6,
        "BlobMaxCircularity": 1.0
    }

<h4>I get an object (which is expected)</h4>

    {
        "SaveAllImages": true,
        "SaveOnlyFailedImages": false,
        "RedThreshold": 215,
        "MaxRedThreshold": 255,
        "BlueThreshold": 215,
        "MaxBlueThreshold": 255,
        "BlobFilterArea": true,
        "BlobMinAreaPx": 2000,
        "BlobMaxAreaPx": 6000,
        "BlobMinThreshold": 10,
        "BlobMaxThreshold": 10000,
        "BlobFilterCircularity": true,
        "BlobMinCircularity": 0.6,
        "BlobMaxCircularity": 1.0
    }

<h4>When I run this same code, using the same json file in a docker container running Debian I get an array (unexpected)</h4>

     [{
         "SaveAllImages": true,
         "SaveOnlyFailedImages": false,
         "RedThreshold": 215,
         "MaxRedThreshold": 255,
         "BlueThreshold": 215,
         "MaxBlueThreshold": 255,
         "BlobFilterArea": true,
         "BlobMinAreaPx": 2000,
         "BlobMaxAreaPx": 6000,
         "BlobMinThreshold": 10,
         "BlobMaxThreshold": 10000,
         "BlobFilterCircularity": true,
         "BlobMinCircularity": 0.6,
         "BlobMaxCircularity": 1.0
    }]

This of course causes an exception be to thrown:

    [json.exception.type_error.306] cannot use value() with array

#### Can you provide a small but working code example?

<h3>Reading the file</h3>

        std::ifstream file{ config };
        if ( !file.is_open( ) )
        {
            throw create_error( 
                "Get configuration error: Failed to open file {}\n", config );
        }

       // This succeeds.
        try { return json::parse( file ); }
        catch( const json::exception& ex )
        {
            throw create_error( 
                "Get configuration error: Deserialization failed {}\n", ex.what( ) );
        } 

<h3>Reading a property</h3>

    // This throws the exception specified above.
    double threshold{ json_reader.value( "BlueThreshold", 215.0 ) };

#### What is the expected behavior?

I expect deserialization to be the same for both platforms.

#### And what is the actual behavior instead?

On macOS I get a json `object` back, on Linux I get an `array` back.

#### Which compiler and operating system are you using?

- Compiler: g++ (Linux) and clang (macOS)

- Operating system: 
- Host: macOS Catalina 
- Container: Debian 

#### Which version of the library did you use?

- [ ] latest release version 3.9.0
- [x] other release - please state the version: 3.7.3 (Installed from vcpkg)
- [ ] the `develop` branch

I'm currently exposing the json file to the container via  [osxfs](https://docs.docker.com/docker-for-mac/osxfs/)

**Comment by nlohmann** [comment] 2020-08-05 10:31
There is a known (and still open) issue that when you initialize `json` variables with braces, they trigger the initializer list constructor and return an array. For instance `json j {1};` creates the JSON array `[1]` instead of just the number `1`.

Can you please double check whether it's really parsing the value and not a brace initialization?

**Comment by wbuck** [comment] 2020-08-05 11:52
@nlohmann Oh I see, so if I'm doing something like this:

    json get_config( std::string_view path )
    {
        std::ifstream file{ config };
        return json::parse( file );
    }

    void some_func( )
    {
         // This could trigger the ctor taking an initializer list?
        auto config{ get_config( "/path/to/json" ) };
    }

Maybe it's time I stop using brace initialization...

**Comment by wbuck** [comment] 2020-08-05 13:53
Yes this issue is related to [2311](https://github.com/nlohmann/json/issues/2311)
I can close this issue if you'd like.

**Comment by nlohmann** [comment] 2020-08-05 20:30
Duplicate of #2311.

**Closed by nlohmann** 2020-08-05 20:30 UTC
Labels: kind: bug, state: needs more info
