### ISSUE TITLE
basic_json has no member "parse"

### ISSUE THREAD

**Issue by Ruud-cb** [nlohmann/json#1731] opened 2019-08-28 11:33 UTC
- What is the issue you have?

Copied the json.hpp file (v3.7.0) from release into my C++ project, the IDE (VS2019) instantly reports problems with 2 issues:

> class "nlohmann:basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann:adl_serializer>" has no member "parse".

https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L22516

And one error I am a little bit less concerned about because I don't need it to parse a json:

> class "nlohmann:basic_json<std::map, std::vector, std::string, bool, int64_t, uint64_t, double, std::allocator, nlohmann:adl_serializer>" has no member "swap".

https://github.com/nlohmann/json/blob/develop/single_include/nlohmann/json.hpp#L22495

- Please describe the steps to reproduce the issue. Can you provide a small but working code example?

1. Create a new C++ Dynamic Link Library Project in VS2019
2. Add json.hpp
3. See errors

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?

Visual Studio 2019 (v142)
Also tried Visual Studio 2017 (v141) but that even gave me more issues.

- Did you use a released version of the library or the version from the `develop` branch?

- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

FYI: I am a C++ noob

**Comment by t-b** [comment] 2019-08-29 10:53
See https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a265a473e939184aa42655c9ccdf34e58.html#a265a473e939184aa42655c9ccdf34e58 for an example how to use the static parse method.

**Comment by kyeonghopark** [comment] 2019-09-09 02:07
It seems just an error from Visual Studio IntelliSense, not an actual compiler.
Maybe a bug of IntelliSense?

**Comment by AmFobes** [comment] 2019-09-14 18:37
Visual Studio 2019 (16.2.5) suffers from the same IntelliSense bug, hoping for a fix soon.

**Comment by nlohmann** [comment] 2019-09-16 20:06
As the issue is not related to the library, but rather IntelliSense, I'm closing the issue.

**Closed by nlohmann** 2019-09-16 20:06 UTC
Labels: kind: bug, platform: visual studio, solution: proposed fix

**Comment by asfarley** [comment] 2019-10-07 16:08
For anyone still running into this, there's a workaround available. Add the following flag to 'Additional Options' under your project's Configuration Properties -> C/C++ -> Command Line options.

`Zc:__cplusplus`

![Workaround](https://user-images.githubusercontent.com/1622578/66328728-6b32e680-e8ea-11e9-809c-b5524f040dcf.png)

**Comment by monkey0506** [comment] 2019-10-15 04:22
> For anyone still running into this, there's a workaround available. Add the following flag to 'Additional Options' under your project's Configuration Properties -> C/C++ -> Command Line options.

I'm absolutely floored by the fact that this simple compiler switch actually makes IntelliSense play nicely with complex template code. It's much more pleasant than what I was doing before (stubbing the entire API inside of `#ifdef __INTELLISENSE__` blocks).
