### ISSUE TITLE
unused-parameter on OSX when Diagnostics is off

### ISSUE THREAD

**Issue by bflorac** [nlohmann/json#2658] opened 2021-03-01 04:42 UTC
#### What is the issue you have?
When compiling on OSX (CLANG) the default compiler state has unused-parameter turn on. This issues warnings for json.hpp, class exception, function diagnostics(), because the leaf_element parameter is not used. A simple (void)(leaf_element) in the #ELSE clause will resolve the issue.

#### Please describe the steps to reproduce the issue.

1.
2.
3.

#### Which compiler and operating system are you using?

- Compiler: CLANG
- Operating system: OSX

#### Which version of the library did you use?

- [x ] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by gregmarr** [comment] 2021-03-01 18:07
Same as #2646 
@nlohmann This should be a simple fix.

**Comment by eike-fokken** [comment] 2021-03-02 19:23
If you are ok with using standard specific macros, you could also use 
the [[maybe_unused]] specifier for c++17 and later.
It has the (albeit small) advantage that nothing unneccessary is done at runtime even when all optimization is turned off.

**Comment by nlohmann** [comment] 2021-03-23 06:19
Duplicate of #2646.

**Closed by nlohmann** 2021-03-23 06:19 UTC
Labels: kind: bug
