### ISSUE TITLE
Error occurred when converting nlohmann::json to std::any

### ISSUE THREAD

**Issue by kotori2** [nlohmann/json#3428] opened 2022-04-07 18:24 UTC
### Description

I would like to store objects in a `std::map<std::string, std::any>`. But converting `nlohmann::json` to `std::any` throws error `type must be string, but is `

I can only reproduce this issue on Windows. macOS seems working fine. 

### Reproduction steps

Minimal test case:
```
#include <any>
#include <nlohmann/json.hpp>

int main() {
    nlohmann::json j;
    std::any &&a = j;
    return 0;
}
```

### Expected vs. actual results

Expected: Runs without error
Actual: Exception: Exception 0xe06d7363 encountered at address 0x7ffa855c466c

### Error messages

```Shell
<unknown> 0x00007ffa855c466c
<unknown> 0x00007ffa6dcfb660
nlohmann::detail::from_json<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > >,std::any,0>(const nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > > &,std::any &) from_json.hpp:118
nlohmann::detail::from_json_fn::operator()<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > >,std::any &>(const nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > > &,std::any &) from_json.hpp:480
nlohmann::adl_serializer<std::any,void>::from_json<nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > > const &,std::any>(const nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > > &,std::any &) adl_serializer.hpp:25
nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > >::get_impl<std::any,0>(priority_tag<0>) json.hpp:1613
nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > >::get<std::any,std::any>() json.hpp:1756
nlohmann::basic_json<std::map,std::vector,std::basic_string<char,std::char_traits<char>,std::allocator<char> >,bool,__int64,unsigned __int64,double,std::allocator,nlohmann::adl_serializer,std::vector<unsigned char,std::allocator<unsigned char> > >::operator<std::any,0> std::any() json.hpp:1900
main() main.cpp:7
invoke_main() 0x00007ff7cb0d12c9
__scrt_common_main_seh() 0x00007ff7cb0d116e
__scrt_common_main() 0x00007ff7cb0d102e
mainCRTStartup(void *) 0x00007ff7cb0d135e
<unknown> 0x00007ffa872d54e0
<unknown> 0x00007ffa87e8485b
```
```


### Compiler and operating system

MSVC 19.31.31104 on Windows 11 21H2

### Library version

current develop 15fa6a342af7b51cb51a22599026e01f1d81957b

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment] 2022-04-07 18:32
Seems to work just fine for me with trunk:
https://godbolt.org/z/jcv3Ejsnd

(GCC 11, Clang trunk, MSVC latest)

**Comment by nlohmann** [comment] 2022-04-11 18:07
Can I close this issue then?

**Comment by kotori2** [comment] 2022-04-11 18:14
But I didn't get it…… why `std::any` is a string type?

**Comment by nlohmann** [comment] 2022-04-11 18:17
I cannot reproduce the runtime error.

**Comment by falbrechtskirchinger** [comment] 2022-04-11 18:20
> I cannot reproduce the runtime error.

https://godbolt.org/z/T8fnsrKPz
This reproduces the issue.

**Comment by nlohmann** [comment] 2022-04-11 18:33
Thanks! So this only occurs on MSVC? Very strange. I would need to see the stack trace from the exception and the state of the `basic_json` value.

**Comment by falbrechtskirchinger** [comment] 2022-04-11 18:40
> Thanks! So this only occurs on MSVC? Very strange. I would need to see the stack trace from the exception and the state of the `basic_json` value.

I just tried again with Clang (trunk) and it works just fine with the rvalue ref. `a.type()` indicates it does contain a `basic_json` as expected. I can try to step through it with a debugger when built with GCC/Clang to see how it differs from the MSVC stack trace above. But that would have to wait until tomorrow.

**Comment by kotori2** [comment] 2022-04-11 19:55
> Also, it only happens in the rvalue ref case

It seems on `Apple Clang 13.1.6` and `gcc 9.4.0` the copy constructor was called. The stack is also different from MSVC. 

> I would need to see the stack trace from the exception

I've posted the stack trace in the `Error messages` section.
![image](https://user-images.githubusercontent.com/17663689/162819057-3ca6466b-39e9-4432-a260-128705a752aa.png)

**Comment by falbrechtskirchinger** [comment] 2022-04-12 05:40
I think this can be fixed by conditionally excluding `std::any` from being implicitly converted. Running it through CI right now.

**Closed** 2022-04-12 12:08 UTC
Labels: kind: bug, confirmed, platform: visual studio, solution: proposed fix, release item: :bug: bug fix

**Comment by kotori2** [comment] 2022-04-12 12:30
@falbrechtskirchinger @nlohmann Thanks for your hard work!
