### ISSUE TITLE
to/from_msgpack only works with standard typization

### ISSUE THREAD

**Issue by phyz777** [nlohmann/json#1021] opened 2018-03-22 00:15 UTC
The to/from_msgpack functions only work for standard typization of nlohmann::basic_json. 

Using nlohmann::basic_json<std::map, std::vector, std::string, bool, std::int32_t, std::uint32_t, float> produces the following error: 

parse error at 1472: expected a MessagePack string; last byte: 0x68

The error occurs when I put an object into a msgpack, send it over the network, then reconstruct the object using from_msgpack. When I use nlohmann::json instead, everything works fine. 

System is linux, compiler is g++, version 7.2.1, nlohmann::json is version 3.1.2.

**Comment by nlohmann** [comment] 2018-03-22 06:21
Could you provide a small example that triggers the error?

**Comment by phyz777** [comment] 2018-03-24 12:59
I am working on it. 
Meanwhile, I came across something similar. I am not even sure whether this is one is a bug: 

`#include <iostream>
#include "json.hpp"

// using json=nlohmann::json;
using json=nlohmann::basic_json<std::map, std::vector, std::string, bool, std::int32_t, std::uint32_t, float>;

int main()
{
    double Value2 = 1000.0;

    json j;
    j["Key1"] = "Value1";
    j["Key2"] = Value2;

    std::vector<uint8_t> v = json::to_msgpack(j);
    json k = json::from_msgpack(v);

    std::cout << k.dump(4) << std::endl;

    return 0;
}
`
Is nlohmann::json supposed to safely convert types where necessary? This one throws nlohmann::detail::parse_error

**Comment by nlohmann** [comment] 2018-03-27 18:07
The issue is that while the library respects the provided number types in the serialization, it does not add the correct prefixes. For instance, it serializes the `float` value correctly with 4 bytes, but adds a `0xcb` byte (float 64) as type prefix.

To fix this issue, the serialization must derive the MessagePack (and most probably also CBOR and UBJSON) type prefix from the templated type. I am not sure about a nice way, but I think functions like `std::is_floating_point` would be my friend.

**Comment by nlohmann** [comment] 2018-03-28 17:51
I opened branch https://github.com/nlohmann/json/tree/feature/issue1021 which supports `float` as floating-point type for all binary formats.

@phyz777 Could you check if this fixes your issue?

**Comment by nlohmann** [comment] 2018-04-04 19:01
@phyz777 Could you check if this fixes your issue?

**Comment by nlohmann** [comment] 2018-04-08 07:29
I merged the fix. If there is still an issue, please let me know.

**Closed by nlohmann** 2018-04-08 07:29 UTC
Labels: aspect: binary formats, confirmed, solution: proposed fix
