### ISSUE TITLE
json constructor does not support std::optional

### ISSUE THREAD

**Issue by gzliudan** [nlohmann/json#2214] opened 2020-06-24 09:28 UTC
I'm using clang 9.0 which support C++17, but below codes can't pass compile when I use nlohmann::json:

```cpp
std::optional<int> value;
auto json = nlohmann::json{{"opt", value}};

instead, I have to use below codes:
if (value) {
    json = nlohmann::json{{"opt", *value}};
} else {
    json = nlohmann::json{{"opt", nullptr}};
}
```

**Comment by dota17** [comment] 2020-06-24 09:38
Please See #1749 .
There is a PR #2117 , but it didn't merge into `develop` because there are some problems.

**Comment by nlohmann** [comment] 2020-06-24 09:49
Duplicate of #1749.

**Closed** 2020-06-24 09:49 UTC
Labels: kind: bug, solution: duplicate
