### ISSUE TITLE
warning under gcc 10.1

### ISSUE THREAD

**Issue by user1095108** [nlohmann/json#2110] opened 2020-05-15 09:52 UTC
json/single_include/nlohmann/json.hpp: In static member function 'static CharType nlohmann::detail::binary_writer<BasicJsonType, CharType>::to_char_type(uint8_t)':
json/single_include/nlohmann/json.hpp:12595:28: warning: 'template<class _Tp> struct std::is_pod' is deprecated: use is_standard_layout && is_trivial instead [-Wdeprecated-declarations]
12595 |         static_assert(std::is_pod<CharType>::value, "CharType must be POD");

**Comment by nlohmann** [comment] 2020-05-15 09:53
Duplicate of #2019, #1913, and fixed in develop branch and next release 3.8.0.

**Closed** 2020-05-15 09:53 UTC
Labels: kind: bug, solution: duplicate, solution: proposed fix
