### ISSUE TITLE
How to make sure a string or string literal is a valid JSON?

### ISSUE THREAD

**Issue by Substance12** [nlohmann/json#458] opened 2017-02-16 19:05 UTC
I'm gonna be sending strings to the parser that might or might not be valid JSONs and I need a way to check they are. I'm programming for a Nintendo 3DS, but using try to catch an exception does not work and the application hangs anyway if it finds an error while parsing. What can I do?

**Comment by jmazzola** [comment] 2017-02-16 23:48
it'd be nice to have a method perhaps a boolean to "validate" json. Similar to how this website works:

http://codebeautify.org/jsonviewer#

**Comment by gregmarr** [comment] 2017-02-17 00:37
There is a library that just does validation and supports this parser:
https://github.com/tristanpenman/valijson

**Comment by Substance12** [comment] 2017-02-17 02:35
That doesn't do what I need, I asked the author. If I provide a non-valid JSON it'll still hang :/

**Comment by gregmarr** [comment] 2017-02-17 02:42
Really, a hang?  That's very surprising.  Can you share a sample of the json that causes a hang?

**Comment by Substance12** [comment] 2017-02-17 02:44
I doubt it's got something to do with the JSON, it's because there is no good way that I know of handling exceptions when programming for a Nintendo 3DS so the program will just freeze.

**Comment by gregmarr** [comment] 2017-02-17 02:58
JSON for Modern C++ Version 2.1.0
@nlohmann nlohmann released this 19 days ago · 56 commits to develop since this release

Release date: 2017-01-28

✨ Exceptions can now be switched off. This can be done by defining the preprocessor symbol JSON_NOEXCEPTION or by passing -fno-exceptions to your compiler. In case the code would usually thrown an exception, abort() is now called.

**Comment by gregmarr** [comment] 2017-02-17 02:59
Oh, that probably doesn't help much either, as it calls abort.

**Comment by gregmarr** [comment] 2017-02-17 03:00
So what you really need is for the library to return an error code instead of throwing or aborting when calling `parse()`.

**Comment by Substance12** [comment] 2017-02-17 03:00
Yes, pretty much.

**Comment by nlohmann** [comment] 2017-02-17 09:53
I understand the issue. Inside `parse_internal()` all exceptions are thrown by `expect()`/`unexpect()`. (https://github.com/nlohmann/json/blob/develop/src/json.hpp#L11455) We may use a different replacement for `JSON_THROW` there, but still would have the problem of leaving the function immediately in case of an error.

**Comment by Substance12** [comment] 2017-02-17 15:50
Would it be possible to return an empty json object instead?

**Comment by nlohmann** [comment] 2017-02-17 17:18
If replacing the throw call is possible, returning a discarded object would be better. You would check it with `is_discarded()`.

**Comment by Substance12** [comment] 2017-02-18 00:02
Hey, commenting the JSON_THROW part on except() and unexcept() and then using an "if (json::parse(string) != NULL)" seems to work!

**Comment by nlohmann** [comment] 2017-02-19 19:52
To properly provide a solution for this issue, I think it would be best to have a dedicated check function that returns a boolean and does not create any `basic_json` values at all.

**Comment by Substance12** [comment] 2017-02-19 19:54
Yeah, a well-programmed function would be a better idea, but for now this trick works for me.

**Comment by ronaaron** [comment] 2017-03-23 08:00
I'd definitely add my vote for a validation function.  I'm having trouble where the exceptions aren't caught (in a multi-thread app, clang++ on linux) and it's a critical bit of infrastructure.

**Comment by nlohmann** [comment] 2017-03-23 12:19
Such a validation function should be added to 3.0.0.

**Comment by ronaaron** [comment] 2017-03-23 12:24
Thank you!

**Comment by user1095108** [comment] 2017-03-31 08:06
the function has to have a noexcept specifier.

**Comment by nlohmann** [comment] 2017-03-31 08:07
This is not possible, because then we would need noexpect functions to read from streams.

**Comment by user1095108** [comment] 2017-03-31 08:09
? streams don't necessarily throw, actually they don't by default.

**Comment by theodelrieu** [comment] 2017-03-31 08:12
Even if we don't have `std::optional` nor `std::expected` right now, maybe a `json::parse_optional` method would be great. There is the same kind of method in `Boost.PropertyTree` for example.

It could return a `std::unique_ptr`, which is not ideal, but gets the job done, what do you think?

**Comment by user1095108** [comment] 2017-03-31 08:26
the functions are nothrow, but if you can disable/restore the throwing at runtime and in that case noexcept is OK.

**Comment by nlohmann** [comment] 2017-03-31 08:28
I meant noexcept. I cannot declare a validator function `noexcept` if it calls functions that itself are not marked `noexcept`.

**Comment by theodelrieu** [comment] 2017-03-31 08:30
You can always `try { } catch (...) {return false;}`

**Comment by user1095108** [comment] 2017-03-31 08:32
@nlohmann you can, if you make sure, that the non-marked functions won't throw, otherwise, there will be an abort.

**Comment by nlohmann** [comment] 2017-03-31 08:33
Well. We agree we need a validation function. The rest shall be discussed once we have an implementation.

**Comment by nlohmann** [comment] 2017-04-24 15:48
A first acceptor function is implemented in 8b9f51179e57c758da4a7042831e68901606d5c7. I would be happy for any feedback before I start adding a public interface.

**Comment by nlohmann** [comment] 2017-05-07 12:49
The mentioned acceptor function is now merged to the `develop` branch. It still lacks a public interface, yet I am looking forward to receiving feedback.

**Comment by nlohmann** [comment] 2017-05-09 14:09
Related to https://github.com/nlohmann/json/issues/478#issuecomment-299977404.

**Comment by 1Hyena** [comment] 2017-05-16 07:37
I have the same issue (sort of). My process exits because sometimes the JSON I receive from the API is invalid. I used to catch that exception as `std::invalid_argument` but now it doesn't work any more. It seems that there are more exceptions the `parse` function can throw. It's sad that there is no nothrow option because in most cases code can be implemented without exceptions anyway. So, my question is, what exceptions should I try-catch when calling `nlohmann::json::parse` ? I cannot allow the overhead of validating before parsing. For the record, this is the exception that I get:
```
terminate called after throwing an instance of 'nlohmann::detail::parse_error'
  what():  [json.exception.parse_error.101] parse error at 1: syntax error - invalid literal; last read '<'
Caught signal 6 (Aborted).
```
catching everything with `...` is funny because it pretty much defeats the purpose of exceptions anyway.

What is the complete list of exceptions that I must catch when calling `parse` ? My code is very critical and must not fail. If you add exceptions or change their names and I upgrade the nlohmann header then things will break in my application and this is very bad.

**Comment by nlohmann** [comment] 2017-05-16 07:44
You are working with an unreleased 3.x version. There, the exceptions have been overworked. There is no final documentation, but you can find a preliminary documentation in the first quarter of the json.hpp file (look for a large table). If you use a released version, your old code should be fine.

**Comment by 1Hyena** [comment] 2017-05-16 07:51
@nlohmann ah thanks, I was suspecting that. I will better revert back to the latest release then.

Also, to other readers facing similar problems, you might want to try: `std::current_exception`
http://en.cppreference.com/w/cpp/error/current_exception

**Comment by nlohmann** [comment] 2017-06-16 17:30
With b27d2adcbe7a3bcf2f994ef2ce0ed4acefda204a I added a family static `bool accept()` functions that accept the same parameters as the `parse()` family (without the callback parameter) and return true if and only if the provided input is a valid JSON text. In case a parse error occurs, no exception is thrown. In fact, I currently can only think of exceptions if a passed input stream or an iterator range is invalid.

I would be happy for feedback!

**Comment by 1Hyena** [comment] 2017-06-17 08:57
@nlohmann 
But the accept function does not produce the JSON object then? It can only be used to validate the input but if you want to validate AND produce the JSON object then you have to first call accept and then parse? This would be slow.

Why not make a version of the `parse` function that accepts 2 arguments instead of 1. The first argument is the string to parse and the second (optional) argument is a pointer to the `nlohmann::json` object where to store the parsed JSON on success. Upon failure the function returns false and does not change the pointed JSON object.

The declaration of this function would look like this:
`bool nlohmann::parse(const char *json_string, nlohmann::json *to);`
It wouldn't throw anything ever.

**Comment by nlohmann** [comment] 2017-06-17 09:08
Then I misunderstood what was meant by "validation function".

**Comment by nlohmann** [comment] 2017-06-17 09:16
I shall think of a solution. I do not really like the approach with a pointer though.

**Comment by 1Hyena** [comment] 2017-06-17 09:41
@nlohmann sure it was just an example of the concept. You can pass by reference if you want to. I'm just more a pointer-person.

**Comment by 1Hyena** [comment] 2017-06-17 09:42
@nlohmann but there is one advantage to my proposed pointer concept. It allows you to pass nullptr as an argument which would instruct the parse function to not produce the nlohmann::json object but only validate the string and return either true or false. if you pass by reference then you can't pass a nullptr by reference you know :P

**Comment by 1Hyena** [comment] 2017-06-17 09:45
Example usecase
```C++
nlohmann::json obj;
if (!nlohmann::parse(json_str, &obj) printf("Invalid json string: %s", json_str.c_str());
if (!nlohmann::parse(json_str, nullptr) printf("Invalid json string: %s", json_str.c_str());
```

**Comment by nlohmann** [comment] 2017-06-17 11:17
The problem is that the current implementation of `parse` already has a last parameter of type `parser_callback_t` with a default parameter. For this function, I am not sure whether overloading is the way to go. Furthermore, we support six different inputs to read from (string, char pointer, ...) - I do not really like this explosion in parse-related functions.

One way (and I am not convinced it is the best) would be to expose the parser class to the user who then can decide which function to call. This would avoid implementing six versions of all possible parse function. Even better, we may use the same class to cope with MessagePack and CBOR.

Hypothetical example:

```cpp
json::parser p(my_input);
json j;

bool x = p.parse(j);
j = p.parse(my_callback);
```

If we add an `operator json()` to this parser class, we may still write `json j = json::parse(my_input)`.

What do you think?

**Comment by nlohmann** [comment] 2017-06-17 12:12
Opened #623 as place to discuss the structure of the parsing functions.

**Comment by CodeMasterYi** [comment] 2017-07-10 08:56
> Well. We agree we need a validation function.

This is what i need! Aha~ #640

**Comment by nlohmann** [comment] 2017-07-23 21:13
FYI: It is now possible to call `static bool accept(i)` with any type `i` from which an input adapter can be constructed. Basically, `i` can have the same types as `static basic_json parse(i)`. This function returns true iff the input contains a valid serialized JSON value. No exceptions are thrown in case of an error. The function is not `noexcept`, because reading from an input (e.g., an `std::ifstream`) may throw.

Next thing I would work on is a way to configure `parse` not to throw an exception in case of a parse error.

**Comment by nlohmann** [comment] 2017-07-27 19:03
You can now pass a boolean `allow_exceptions` to the parse functions. If it is `false`, no exceptions are thrown in case of a parse error. Instead, parsing is stopped at the first error and a JSON value of type "discarded" (check with `is_discarded()`) is returned.

**Comment by nlohmann** [comment] 2017-07-30 18:09
Done.

**Closed by nlohmann** 2017-07-30 18:09 UTC
Labels: kind: enhancement/improvement, solution: proposed fix

**Comment by houglum** [comment] 2018-10-04 02:54
> You can now pass a boolean `allow_exceptions` to the parse functions. If it is `false`, no exceptions are thrown in case of a parse error. Instead, parsing is stopped at the first error and a JSON value of type "discarded" (check with `is_discarded()`) is returned.

Looks like that's correct, given a conversation I had today to test this :) However, [the docs](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_aabe623bc8304c2ba92d96d91f390fab4.html) indicate that this can't happen:

>This function will always be false for JSON values after parsing. That is, discarded values **can only occur during parsing**, but will be removed when inside a structured value or replaced by null in other cases.

**Comment by nlohmann** [comment] 2018-10-04 06:10
@houglum Is there an issue?

**Comment by houglum** [comment] 2018-10-04 07:02
Just that (I believe) the docs need to be updated.  They say that `is_discarded()` will **always** be false after parsing, but that's only the case if `allow_exceptions` was set to true, IIUC. The docs should be updated to reflect the fact that if `allow_exceptions` is set to false, in the case of a parse error, calling `is_discarded()` on the value returned from `parse()` will return true.

**Comment by mohammadrasekh68** [comment] 2019-08-30 09:36
Im using Accept method to check if my file is a valid Json or not, 
the problem is if i do as follow : 
`		ifstream Valid(jsonFile);
		if(Valid.is_open())
		{
			if(!json::accept(Valid))
			{

				DLTLOG( DLT_LOG_ERROR,jsonFile," is not a valid Json file"); //logging
				return -1;
			}
			JsonObject=json::parse(Valid); // errors happen here
			Valid.close();
		}`
I will get segmentation error (core dump) 
so im force to do this : 
`
		ifstream Valid(jsonFile);
		if(Valid.is_open())
		{
			if(!json::accept(Valid))
			{

				DLTLOG( DLT_LOG_ERROR,jsonFile," is not a valid Json file");
				return -1;
			}
			Valid.close();
		}
		else
		{
			DLTLOG(DLT_LOG_ERROR,"JsonFile : ",jsonFile," Not founded");
			return -1;
		}
		ifstream ifs(jsonFile);

		DLTLOG(DLT_LOG_INFO,"Converting ",jsonFile," JsonFile To JsonObject");
		JsonObject=json::parse(ifs);
		ifs.close();
`
does Accept method, delete my ifstream object?

**Comment by gregmarr** [comment] 2019-08-30 13:33
No, but it does read all of the content.  You need to reset it to the beginning before you can read from it again.  
https://en.cppreference.com/w/cpp/io/basic_istream/seekg

**Comment by tawmoto** [comment] 2020-10-16 08:06
Does anyone knows if there is there a performance difference between `accept` and `parse() + is_discarded()` ?
Thank you

**Comment by 1Hyena** [comment] 2020-10-16 08:23
@tawmoto I personally threw out all uses of nlohmann::json from my project because it is bloatware. Not only does it expect you to use exceptions on a regular basis (anti-pattern as the use of exceptions should be an exception itself), but its most fundamental use-case of turning a string into a valid JSON representation can be done in 150 lines of C++ (includes JSON escaping, UTF-8 parsing and does *not* rely on exceptions).

If speed is important to you, I highly suggest not using nlohmann::json. Serialized JSON is such a trivial format that doing it "manually" makes much more sense than relying on some header-only library. If it is acceptable for you to concatenate strings in order to make up SQL statements, then it should be equally acceptable to the same for JSON serialization. Only if you need to deserialize JSON you might want to use a library, but then you might as well as consider the amazing Linux tool known as `jq`.

**Comment by tawmoto** [comment] 2020-10-16 08:50
@1Hyena Thank you for the answer, speed is important but not mandatory. I have a curl connection which takes 20-30 times more than the parsing, so it's ok.
I don't agree with "parsing" manually, many teams uses this approach and the cloud is overcrowded with a lot of garbage, I preffer to use a well-tested library. At least my jsons are not trivial at all, I have vectors in vectors of structures, which I am reading/writing in 1 line using this great parser. :-)

**Comment by 1Hyena** [comment] 2020-10-16 09:01
@tawmoto 
In case you're using the command line version of `curl`, you should really take a look at what `jq` has to offer. It's such a standard tool these days and in combination with GNU `parallel` it allows you to build horizontally scalable applications in a breeze.

**Comment by nlohmann** [comment] 2020-10-16 13:16
> Does anyone knows if there is there a performance difference between `accept` and `parse() + is_discarded()` ?

Accept is not building a DOM representation and is therefore much faster.

**Comment by nlohmann** [comment] 2020-10-16 13:19
> @tawmoto I personally threw out all uses of nlohmann::json from my project because it is bloatware.

The library offers more than just parsing. If you do not need this, than this library may not be for you.

> Not only does it expect you to use exceptions on a regular basis (anti-pattern as the use of exceptions should be an exception itself), but its most fundamental use-case of turning a string into a valid JSON representation can be done in 150 lines of C++ (includes JSON escaping, UTF-8 parsing and does **not** rely on exceptions).

You can in fact switch off exceptions and still use the library.

I would be really interested in seeing the 150 lines of C++ code.

**Comment by 1Hyena** [comment] 2020-10-16 14:03
I would share the code but it's proprietary. The trick is to use lambdas for reporting valid and invalid byte sequences back to the caller. UTF8 validation is 80 lines. JSON escaping is 100 lines. Line width limit is 80 symbols. The `escape_json` function calls the `parse_utf8` function and does the JSON escaping in the `report_valid` lambda that is called on valid UTF8 sequences by the `parse_utf8` function.

The declarations of the said functions are given below.

```C++
size_t escape_json(
    const char *str,
    std::function<bool(const char *, size_t)> report_valid,
    std::function<bool(const char *, size_t)> report_invalid,
    size_t max_symbols, size_t max_bytes
);

size_t parse_utf8(
    const char *str,
    std::function<bool(const char *, size_t)> report_valid,
    std::function<bool(const char *, size_t)> report_invalid,
    size_t max_symbols, size_t max_bytes
);
```
