### ISSUE TITLE
error C4996: 'strerror' when reading file

### ISSUE THREAD

**Issue by nours59** [nlohmann/json#422] opened 2017-01-08 10:58 UTC
Hello (sorry for my english...),

I have an error when reading file,with this code :
`	std::ifstream i(fileName);
	nlohmann::json j;
	i >> j;
	std::cout << j;
`
here is the error message:
`warning C4996: 'strerror': This function or variable may be unsafe. Consider using strerror_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.`

I'm on Visual Studio 2017, and to avoid this message i have to disable SDL Check, so compiler consider it as simple warning, but i think this issue should be revised

Many thanks in advance

**Comment by nlohmann** [comment] 2017-01-08 11:50
Duplicate of #403. Fixed since version 2.0.10.

**Closed by nlohmann** 2017-01-08 11:50 UTC
Labels: solution: duplicate
