### ISSUE TITLE
document that implicit js -> primitive conversion does not work for std::string::value_type and why

### ISSUE THREAD

**Issue by weber-martin** [nlohmann/json#1052] opened 2018-04-12 12:05 UTC
I expect to be able to convert from and to any C++ primitive type.

I can convert from and to json from basically any type but a plain "char". If trying to do so, I'm getting a compile error:

```
 error: cannot convert ‘nlohmann::json {aka nlohmann::basic_json<>}’ to ‘char’ in initialization
  C c2 = js;
```

Conversion from and to similarly sized `signed char` and `unsigned char` do work as expected, as do conversions from and to `int8_t` and `uint8_t`.

See the following file:
```// minimal.cpp
#include <iostream>
#include <nlohmann/json.hpp>

using nlohmann::json;

template <typename C>
void char_test() {
	C c1 = '?';
	json js = c1;
	C c2 = js;

	std::cout << " c1: " << c1 << " js: " << js << " c2: " << c2 << std::endl;
}

int main(int, char **) {
	char_test<int8_t>();
	char_test<uint8_t>();
	char_test<signed char>();
	char_test<unsigned char>();
	//char_test<char>();
	return 0;
}
```

uncomment the second to last line in `main()` to get the compile error.

Compiled with `g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516` on `Linux 4.12.0-0.bpo.2-amd64 x86_64` invoked as ` g++ -Wextra -Wall -Werror -std=c++11 -I $NLOHMANN_JSON_SINGLE_INCLUDE_DIR -o minimal minimal.cpp`

This is with `nlohmann-json commit 46ec2fddf8774af2f9368bf563dd6e32fa91d77e`

>- If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

Nope, I don't have a cmake 3.8 handy.

**Comment by nlohmann** [comment] 2018-04-12 12:46
This seems to be a duplicate of #276.

**Comment by weber-martin** [comment] 2018-04-12 13:13
Oh ok. Apologies; I looked at the open issues and went to see if I could reproduce it with HEAD, I did not look at the closed "wontfix" issues

Is this documented? It didn't stand out to me when I went over the existing documentation.
If it isn't, then consider this issue a *documentation request*. ;)

**Comment by weber-martin** [comment] 2018-04-16 11:15
A good workaround indeed is using #get<TargetType>(). 
One thing to remember though, in contrast to using the implicit type conversion, is that this might require an extra "template" when calling the ".get" (i.e. `yadda yadda.template get<..>()`) if you are using the json interface in templated code (sure, that's "basic C++ template knowledge" I suppose, but after years this interface is the first one where I had to use it)

**Comment by tamaroth** [comment] 2018-05-23 14:52
I'd like to add a comment.

When using GCC 7.2.0 the following code works perfectly:

```
JSON j = "{ \"happy\": \"maybe\", \"pi\": 3.141 }"_json;
std::string hp(j["happy"]);
```

When compiling the same code with GCC 8.0.1, it does not compile with the following error:

```
error: call of overloaded ‘basic_string(nlohmann::basic_json<>::value_type&)’ is ambiguous
```

Of course using explicit conversion works flawlessly:

```
JSON j = "{ \"happy\": \"maybe\", \"pi\": 3.141 }"_json;
std::string hp(j["happy"].get<std::string>());
```

I thought I mention since 8.0.1 is out.

**Closed** 2018-06-22 20:36 UTC
Labels: documentation
