### ISSUE TITLE
Compile error on Intel compiler running in Windows

### ISSUE THREAD

**Issue by ongjunjie** [nlohmann/json#2346] opened 2020-08-08 17:27 UTC
Unable to compile using Intel compiler in Windows. This is caused by a bug in Hedley nemequ/hedley#39. Opening an issue here to track it.

#### What is the issue you have?

Can't compile. See Hedley issue for details.

#### Please describe the steps to reproduce the issue.

1. Build unit tests using combination of Intel compiler and Windows OS

#### Can you provide a small but working code example?

No.

#### What is the expected behavior?

Unit tests compiles.

#### And what is the actual behavior instead?

Build fails.

#### Which compiler and operating system are you using?

- Compiler: Intel Compiler 18.0
- Operating system: Windows 7

#### Which version of the library did you use?

- [x] latest release version 3.9.1
- [ ] other release - please state the version: ___
- [x] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [x] no - please copy/paste the error message below

```
..\single_include\nlohmann\json.hpp(2366): error : expected a type specifier
        JSON_HEDLEY_NON_NULL(3)
```

**Comment by nlohmann** [comment] 2020-08-12 06:40
Thanks for reporting! I will create a branch with the new Hedley version to see whether the issue is fixed then.

**Comment by ongjunjie** [comment] 2020-08-12 09:01
I did a quick hack by forcing `JSON_HEDLEY_INTEL_VERSION` to always evaluate false. The compilation passes but linking fails.

```
unresolved external symbols "__declspec(dllimport) public: static class std::locale::_Locimp * __cdecl std::locale::_Getgloballocale(void)"
```

The problem stems from doing a `#define private` while including standard headers.
https://github.com/nlohmann/json/blob/b888afe5f45f0ac6381aa5fa93bba7b5fc035354/test/src/unit-convenience.cpp#L32-L35

Unfortunately I don't see any quick fix to this issue. Some ideas:
- Rewrite test to use public interfaces instead of private scoped functions
- Use protected scope instead of private. Protected members can be promoted to public scope in inherited classes.
- Use a macro, for example `JSON_private`, in place of `private` in the library, so it can be modified without affecting STL.

**Comment by nlohmann** [comment] 2020-08-12 09:08
This is a an issue that keeps coming up. Maybe using a macro for certain instances of private is a good idea. I’ll check.

**Comment by nlohmann** [comment] 2020-08-12 11:36
I created PR #2352 for the private/public issue.

**Comment by nlohmann** [comment] 2020-08-13 08:35
@ongjunjie I merged #2352. Could you please try if the tests compile now?

**Comment by ongjunjie** [comment] 2020-08-13 10:10
Unit tests compiles. Passes all tests only if I pass extra flag `/fp:precise` to the compiler. Intel by default uses unsafe floating point optimization.

https://software.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/compiler-option-details/floating-point-options/fp-model-fp.html

**Comment by nlohmann** [comment] 2020-08-13 10:16
Very good! I'll wait for the Hedley release. I will also add a note to the README on the `/fp:precise` flag. Can you tell me which tests fail if the parameter is not set?

**Comment by ongjunjie** [comment] 2020-08-19 08:15
Failing tests when compiled without `/fp:precise` are:
- test-cbor
```
TEST CASE:  CBOR roundtrips
  input from flynn
```
- test-msgpack
```
TEST CASE:  MessagePack roundtrips
  input from msgpack-python
```
- test-testsuites
```
TEST CASE:  compliance tests from nativejson-benchmark
  roundtrip
```

**Comment by susuhuanzhen** [comment] 2020-08-21 06:11
hello ,I can not complier with platform Visual Studio 2017 (v141) ,but  Visual Studio 2015 (v140) works well.

**Comment by ongjunjie** [comment] 2020-08-26 09:28
Build and tests passing with latest develop branch. Possible to close this issue.

**Comment by nlohmann** [comment] 2020-08-29 10:47
I added a note to the README on flag `/fp:precise`.

**Closed by nlohmann** 2020-08-29 10:47 UTC
Labels: kind: bug, platform: icc, release item: :hammer: further change, solution: proposed fix
