### ISSUE TITLE
Copyconstructor inserts original into array with single element

### ISSUE THREAD

**Issue by Mithrandir2k18** [nlohmann/json#1397] opened 2018-12-19 12:32 UTC
Minimal working example:

main.cpp:
```
#include "json.hpp"
#include <iostream>
#include <string>
#include <fstream>

using json = nlohmann::json;

int main(void)
{

        std::ifstream file("test.json");
        json original;
        file >> original;

        std::cout << original.dump(4) << std::endl;

        json copy{original};

        std::cout << copy.dump(4) << std::endl;

        return 0;


}
```

test.json:

```
{

        "objectone" :
        {
                "entryone" : 1
        },

        "objecttwo" :
        {
                "entrytwo" : 2
        }
}
```

Expected Output:
```
{
    "objectone": {
        "entryone": 1
    },
    "objecttwo": {
        "entrytwo": 2
    }
}
{
    "objectone": {
        "entryone": 1
    },
    "objecttwo": {
        "entrytwo": 2
    }
}
```

Current Output:
```
{
    "objectone": {
        "entryone": 1
    },
    "objecttwo": {
        "entrytwo": 2
    }
}
[
    {
        "objectone": {
            "entryone": 1
        },
        "objecttwo": {
            "entrytwo": 2
        }
    }
]
```

- Which compiler and operating system are you using? Is it a [supported compiler](https://github.com/nlohmann/json#supported-compilers)?
g++ 7.3.0 on Ubuntu 18 LTS in WSL 64 Bit Windows10

In my project I wrote a small private function for a class that has a json member. This function loads the json file and returns the object and is called in the initializer list of my classes constructor, similarly to the minimal working example above. It creates this extra json array around the originial which I don't think is expected behaviour.

SIDE NOTE: Thank you for this great library, it is really awesome and intuitive to use. When having to switch my project from python to c++ I never imagined json could be so easy to use!

**Comment by nlohmann** [comment] 2018-12-19 12:36
Initializer lists are interpreted as array. This is a duplicate of #1359 and unfortunately cannot be fixed.

**Closed by nlohmann** 2018-12-19 12:36 UTC

**Comment by Mithrandir2k18** [comment] 2018-12-19 15:45
Just to mention it, a working way to do it is:

` json copy(original);`

instead of

` json copy{original};`
