### ISSUE TITLE
[Question] copy assign json-container to vector

### ISSUE THREAD

**Issue by MrJakmer** [nlohmann/json#635] opened 2017-06-23 13:17 UTC
Hi,

upon the recommendation of Niels Lohmann via e-mail, I want to refer to a question [I asked on stackoverflow](https://stackoverflow.com/q/44543956).

Let me share why I am asking that question: I am trying to search for a "lower bound" in a json-object. I assume this can't work since comparing with a double (or integer) isn't possible. That is why I need the conversion (via copy-assign) to a vector. If the question I referred to is not needed because you can solve the error with the lower bound (see code below), it would be great. But I think using vectors would still be relevant since it would be more efficient, if you use them multiple times.

See the following code:

	#include "json.hpp"

	using json = nlohmann::json;
	using namespace std;

	int main()
	{

		const vector<double> v = { 0 , 10 , 20 ,100 };
		const json j(v);

		json::const_iterator low = lower_bound(j.cbegin(), j.cend(), 11);
		size_t lowerBoundIndex = low - j.begin();
		cout << lowerBoundIndex << endl;

		return 0;
	}

I am using JSON for Modern C++ Version 2.1.1 with Microsoft Visual Studio 2015 Version 14.0.25431.01 Update 3 (regarding to your README the compiler should be okay). My operating system is Windows 7 SP1.

Thanks in advance!

**Comment by nlohmann** [comment] 2017-06-23 14:43
I'm on holiday, but I am confident someone finds an answer.

**Comment by theodelrieu** [comment] 2017-06-23 14:50
I see, the implicit conversion (without calling `get`) fails when types have multiple `operator=`, like `std::vector`.

You can solve this easily however:

```cpp
auto v = j.get<std::vector<double>>();
```

**Comment by MrJakmer** [comment] 2017-06-26 07:15
Thanks, that solves my problem with the conversion. Is it okay for you, if I post this as an answer at stackoverflow in case someone else might have the same problem?

I assumed searching for a lower bound with the code above isn't possible. Could you also explain whether this is correct?

**Comment by theodelrieu** [comment] 2017-06-26 08:17
Of course!

Well, since your array is sorted, this should work as expected.

**Comment by MrJakmer** [comment] 2017-06-26 10:47
Thanks!

It does not work as expected. If I try to compile it, I get the following error:

	Error	C2672	'operator __surrogate_func': no matching overloaded function found

	Error	C2893	Failed to specialize function template 'unknown-type std::less<void>::operator ()(_Ty1 &&,_Ty2 &&) const'

**Comment by theodelrieu** [comment] 2017-06-26 11:28
I see, this is a known bug, that is fixed on develop. Could you try the proposed workaround in #486 ?

**Comment by MrJakmer** [comment] 2017-06-26 12:02
Just using the workaround

	namespace std {
		template <>
		struct less<::nlohmann::detail::value_t>
		{
			bool operator()(::nlohmann::detail::value_t lhs, ::nlohmann::detail::value_t rhs) const noexcept
			{
				return ::nlohmann::detail::operator<(lhs, rhs);
			}
		};
	}

before the main-method should do it, right? I also tried the [json.hpp](https://github.com/nlohmann/json/blob/f4126e4dd84dfb723acb34dd3dbfcd6364b11fb2/src/json.hpp) from the [commit](https://github.com/nlohmann/json/commit/f4126e4dd84dfb723acb34dd3dbfcd6364b11fb2#diff-d525c458d12b63b74e3cf18acbbe25bb) which fixes the bug. Both didn't help. You might be right about this being an unrelated bug.

**Comment by theodelrieu** [comment] 2017-06-26 14:05
Hmm, I'll try to find some time to fix it. What is your test file? The code in your first post?

**Comment by MrJakmer** [comment] 2017-06-26 14:40
Yes.

**Comment by theodelrieu** [comment] 2017-06-27 09:02
After bissecting for a while, I found the commit that fixes your bug, this is 90273e930c135a3f893ef2e303267f76b9b246b5.

You could hijack the `nlohmann` namespace to reproduce the fix, or directly modify the `json.hpp` file.
Since 3.0 won't be released soon enough, I believe those are the only available solutions right now...

**Comment by MrJakmer** [comment] 2017-06-27 10:52
Converting to a vector is not a problem and should be more performant when using lower bound multiple times. I could just use the json.hpp from the develop-branch, right?

**Comment by theodelrieu** [comment] 2017-06-27 11:18
Hmm, I would not recommand using develop frankly... there are some breaking changes.

Converting to `std::vector` is indeed the best way, I forgot that on my previous comment.

**Comment by nlohmann** [comment] 2017-07-08 06:29
Is there anything left to do here?

**Comment by MrJakmer** [comment] 2017-07-08 19:27
As far as I'm concerned, no.

**Comment by nlohmann** [comment] 2017-07-08 19:28
OK. Thanks for checking back!

**Closed by nlohmann** 2017-07-08 19:28 UTC
Labels: kind: question, solution: proposed fix
