### ISSUE TITLE
json_pointer construction bug

### ISSUE THREAD

**Issue by shtinkov** [nlohmann/json#1786] opened 2019-10-10 07:37 UTC
Hi,
I think i hit a bug in json_pointer construction with nlohmann::json 3.7.0. 
When i call json.contains with "/objects/account/actions/select"_json_pointer it works perfect, but calling it with already constructed json_pointer gives false result.
Here is how to reproduce:

```cpp
#include "json.hpp"
#include <iostream>

int main() {
  nlohmann::json test;
  test["objects"]["account"]["actions"]["select"]=65;
  std::string jsonp="/objects/account/actions/select";
  nlohmann::json::json_pointer jp(jsonp);
  std::cout << test << std::endl;
  std::cout << "Is it found with "<< jp<< " : " <<  test.contains(jp) << std::endl;
  std::cout << "Is it found now: " <<  test.contains("/objects/account/actions/select"_json_pointer) << std::endl;
  return 0;
}
```

Output of this is:
```
{"objects":{"account":{"actions":{"select":65}}}}
Is it found with "/objects/account/actions/select" : 0
Is it found now: 1
```

**Comment by nlohmann** [comment] 2019-10-13 09:49
This seems to be a duplicate of #1727 which is fixed in the `develop` version and will be released as version 3.7.1 some time soon. Running with that code, I get the output

```
Is it found with "/objects/account/actions/select" : 1
Is it found now: 1
```

**Closed** 2019-10-15 05:20 UTC
Labels: solution: duplicate, solution: proposed fix
