### ISSUE TITLE
Strange behaviour when creating array with single element

### ISSUE THREAD

**Issue by misos1** [nlohmann/json#3025] opened 2021-09-21 20:49 UTC
#### What is the issue you have?

Seems when calling a function which takes an argument of type json with `{j}` where `j` is of type `json` then is called a copy constructor instead of `basic_json(initializer_list_t init...`.

#### Please describe the steps to reproduce the issue.

1. See example below

#### Can you provide a small but working code example?

``` c++
void func(json j)
{
	printf("%s\n", j.dump().c_str());
}

int main()
{
	json j = 10;
	func({j, j});
	func({10});
	func({j});
}
```

#### What is the expected behavior?

`func({j});` should print "[10]".

#### And what is the actual behavior instead?

`func({j});` prints "10".

```
[10,10]
[10]
10
```

#### Which compiler and operating system are you using?

- Compiler: Apple clang version 12.0.5 (clang-1205.0.22.9)
- Operating system: Darwin

#### Which version of the library did you use?

- [ ] latest release version 3.10.2
- [x] other release - please state the version: 3.7.0
- [ ] the `develop` branch

#### If you experience a compilation error: can you [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests)?

- [ ] yes
- [ ] no - please copy/paste the error message below

**Comment by nlohmann** [comment] 2021-09-22 10:12
This is a duplicate of https://github.com/nlohmann/json/issues/2311. See https://json.nlohmann.me/home/faq/#brace-initialization-yields-arrays.

**Closed** 2021-09-22 10:12 UTC
Labels: kind: bug, solution: duplicate
