### ISSUE TITLE
consider adding a bool json::is_valid(std::string const&) non-member function

### ISSUE THREAD

**Issue by user1095108** [nlohmann/json#541] opened 2017-03-31 07:28 UTC
Consider this scenario. An arbitrary string is provided to an app. The string is supposed to contain valid json, but the app has no way of knowing this. It tries to parse the json with json::parse(), but exceptions are disabled. This means, if the json is not valid, std::abort() will be called and the app will abort and there is no way to prevent this from happening.

**Comment by user1095108** [comment] 2017-03-31 07:36
you may need to add other overloads also, lol. All the overloads that parse() has.

**Comment by nlohmann** [comment] 2017-03-31 07:58
This is a duplicate of #458.

**Closed by nlohmann** 2017-03-31 07:58 UTC
