### ISSUE TITLE
Maintaining JSON package in my CMake

### ISSUE THREAD

**Issue by saurabhbansal90** [nlohmann/json#1987] opened 2020-03-16 09:26 UTC
- Describe what you want to achieve.
I am using CMake 3.1 for my project. I want to keep this json library source in a directory of my source code for easy maintenance and upgrades without any build or install.

- Describe what you tried.
I build this json project and installed it in my PC, and was able to find this package by 'find_package()' and was able to compile it.
But is it possible to have the source code in 1 of the directory and build with it at runtime.

- Describe which system (OS, compiler) you are using.
My host OS is Ubuntu 18, I am using CROSS_COMPILER for arm-cortex-a8.

- Describe which version of the library you are using (release version, develop branch).
Right now I am using develop branch only, but finally will have to use release.

**Comment by saurabhbansal90** [comment] 2020-03-19 09:22
Is this possible to have source in some directory and include it from my CMake file?
Can somebody please help me on this?

**Comment by nlohmann** [comment] 2020-03-19 10:22
I do not fully understand the issue. Could you describe the steps to reproduce the issue?

**Comment by saurabhbansal90** [comment] 2020-03-19 12:25
Hello Nlohmann,

Thanks for response.

Actually I want to integrate this json library in my CMake project.

So one possible way, as explained by you, I can install this library in my machine, and use `find_package` to import in the project.

But can this be done without installing and just by having source code in my project's directory.
Can I use 'find_package' or any other method like `include` to integrate this library with source code only and without installation.

Regards,
Saurabh

**Comment by nlohmann** [comment] 2020-03-20 09:34
You can use `add_subdirectory` and point it to the library and use `nlohmann::json`:

```cmake
add_subdirectory(json)
...
target_link_library(yourtarget PRIVATE nlohmann::json)
```

Then inside the sources of `yourtarget`, you can use

```cpp
#include <nlohmann/json.hpp>
```

**Comment by saurabhbansal90** [comment] 2020-03-23 10:01
Hello Nlohmann, thanks for proposing this solution.
I tried to do the corresponding changes in my CMakeLists.txt file, but when I run `cmake ..`, it is not stopping and running continuously.
By the way, I am cross-compiling my all code for `arm-linux` system and because of that it is having some issues.

I am getting logs as below:
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using the single-header code from /home/eternal/work/waltfirmware/lib/json/single_include/
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/c++
```

Can you please provide some help, how to resolve this issue and build my program.

**Comment by nlohmann** [comment] 2020-03-24 19:37
This seems to be a duplicate of #1809.

**Closed** 2020-04-18 11:19 UTC
Labels: kind: question, solution: proposed fix

**Comment by lletournel** [comment] 2020-04-23 07:25
Hi saurabhbansal90,
I think what you are looking for is provided by the FetchContent module : https://cmake.org/cmake/help/v3.11/module/FetchContent.html

Instead of the find_package, use the following lines (change the json_URL and json_TAG by the repo URL and tag you want to use)

find_package(json QUIET)
if (NOT JSON_FOUND)
    include(FetchContent)

    FetchContent_Declare(json
            GIT_REPOSITORY ${json_URL}
            GIT_TAG ${json_TAG}
            )

    FetchContent_GetProperties(json)
    message(STATUS json)
    message(STATUS ${json_POPULATED})
    message(STATUS ${json_SOURCE_DIR})
    message(STATUS ${json_BINARY_DIR})
    if(NOT json_POPULATED)
        message(STATUS "Downloading, Configuring and Generating 'json' dependency")
        FetchContent_Populate(json)

        # json BUILD OPTIONS
        set(BUILD_SHARED_LIBS TRUE CACHE BOOL "" FORCE)
        set(JSON_BuildTests OFF CACHE BOOL "" FORCE)# CACHE BOOL "Build json tests")
        set(JSON_Install OFF CACHE BOOL "" FORCE)

        add_subdirectory(${json_SOURCE_DIR} ${json_BINARY_DIR})

        message(STATUS "DONE")
    endif()
endif()


if (TARGET json)
    get_target_property(INC json INCLUDE_DIRECTORIES)
    message(STATUS "JSON TARGET : ${INC}")
endif()
