### ISSUE TITLE
Can I disable sorting of json values

### ISSUE THREAD

**Issue by VladimirBalun** [nlohmann/json#2219] opened 2020-06-25 11:51 UTC
Hello, I have the following code: 

`nlohmann::json data = { {"service", "abc" }, { "level", "info" }, {"traceId", "aaabbbccc" }};`
`std::cout << data << std::endl;`

Output will be: 
`{"level":"info","service":"abc","traceId":"aaabbbccc"}`

Can I disable sorting of values for the following output without sorting: 
`{"service":"abc","level":"info","traceId":"aaabbbccc"}`

**Comment by nlohmann** [comment] 2020-06-25 11:53
Duplicate of #2179.

**Closed** 2020-06-25 11:53 UTC
Labels: kind: question, solution: duplicate
