### ISSUE TITLE
icc16 error

### ISSUE THREAD

**Issue by vsakharuk** [nlohmann/json#617] opened 2017-06-13 14:23 UTC
Hello folks,
2.1.1 does not compile with icc 16, while works with clang and gcc.
Error:
`json.hpp(11227): error: expression must have a constant value
                  static_assert(std::is_signed<T>() == std::is_signed<decltype(x)>(), "");
                                                    ^
          detected during:
            instantiation of "bool nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::lexer::strtonum::to(T &) const [with ObjectType=std::map, ArrayType=std::vector, StringType=std::string, BooleanType=bool, NumberIntegerType=int64_t={long}, NumberUnsignedType=uint64_t={unsigned long}, NumberFloatType=double, AllocatorType=std::allocator, JSONSerializer=nlohmann::adl_serializer,
                      T=uint64_t={unsigned long}, <unnamed>=void]" at line 11275`

May I suggest to replace line 11227
`static_assert(std::is_signed<T>() == std::is_signed<decltype(x)>(), "");`
with
`static_assert(std::is_signed<T>::value == std::is_signed<decltype(x)>(), "");`

Regards V.

Edit:

Sorry that patch does not help all the time. This one complies with icc:
`static_assert(std::is_signed<T>::value == std::is_signed<decltype(x)>::value, "")`

**Comment by nlohmann** [comment] 2017-06-13 14:25
For reference: https://github.com/nlohmann/json/blob/v2.1.1/src/json.hpp#L11227

**Comment by nlohmann** [comment] 2017-07-08 14:22
The problem is fixed with the (yet unreleased) 3.x.x series (see `develop` branch). For the 2.x.x series, I do not plan any new releases. With the fix described here, I close this issue. Sorry for the inconvenience.

**Closed** 2017-07-08 14:23 UTC
Labels: solution: proposed fix, solution: wontfix
