### ISSUE TITLE
compile error with clang 5.0 -std=c++1z and no string_view

### ISSUE THREAD

**Issue by phlptp** [nlohmann/json#939] opened 2018-01-28 15:16 UTC
**Bug Report**

Compile error on clang 5.0 with -std=c++1z
```
In file included from XXXX.cpp:32:
XXXX/json.hpp:9913:66: error: no type named
      'string_view' in namespace 'std'
  ...and not std::is_same<ValueType, typename std::string_view>::value
                                     ~~~~~~~~~~~~~~^~~~~~~~~~~
```
All other compilers tested thus far work fine.  

my fix was to simply comment out that line since I wasn't using std::string_view, but but I am guessing there is a reason for including string_view in the  enable_if statement so I don't think my fix is a valid solution and I am not familiar enough with the structures used to integrate a check for the existence of string_view before using it in an is_same template.  

The other options was to include <string_view> if JSON_HAS_CPP_17 is enabled but that didn't seem proper either.

**Comment by nlohmann** [comment] 2018-01-28 15:17
Related: #735.

**Comment by nlohmann** [comment] 2018-01-28 15:21
We do not include `<string_view>`, but assume that it is included by `<string>` (see https://github.com/nlohmann/json/issues/735#issuecomment-334550718). I cannot reproduce the issue, because Travis successfully runs a job with Clang 5 and `-std=c++1z`.

Please have a look at #735 - in particular, if you can include `<string_view>`.

**Comment by phlptp** [comment] 2018-01-28 15:41
I am building with libc++ not libstdc++, on ubuntu 17.10.  In the code I am using it in I use a string_view library that is not from the stl  since it needed to work with string_view objects without requiring c++1z capability on all compilers so it is in a different namespace, I presume that would cause some interesting issues as well but the uses don't overlap in the code.  I think I had the master branch in the code, but develop seems to fail in the same way.  I suppose I should check the compile with libstdc++ and see if it fails in the same way.

**Comment by phlptp** [comment] 2018-01-28 15:48
it compiles properly using libstdc++ and everything else the same, so using libc++ would appear to be the issue.

**Comment by nlohmann** [comment] 2018-01-28 15:49
Thanks for the feedback. Does `<string_view>` work with libc++?

**Comment by phlptp** [comment] 2018-01-28 16:08
No it doesn't,  looks like the libc++ used in Ubuntu 17.10 is version 3.9 and string_view was not integrated until 4.0, but the compiler itself has c++17 support and the 3.9 library has partial support.

**Comment by nlohmann** [comment] 2018-01-28 16:09
Thanks. Then this seems to be a duplicate of #735.

**Closed by nlohmann** 2018-01-28 16:09 UTC
