### ISSUE TITLE
Ambiguous compare operators with clang-5.0

### ISSUE THREAD

**Issue by pboettch** [nlohmann/json#547] opened 2017-04-05 07:47 UTC
This code:

```c++
msg["level"] = -80;
if (msg["level"] < -115) {
    ////
}
```
Gives me a bunch of 

`error: use of overloaded operator '>=' is ambiguous (with operand types 'int' and 'const value_type' (aka 'const nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char>, bool, long, unsigned long, double, std::allocator, adl_serializer>'))`

errors when using clang-5.0 (5.0.0-svn294894-1) . Where with gcc 6.3 everything is fine, no moaning.

I know that this version of clang is from the dev-tree (iiuc), but I'm creating this issue to see whether there is something to be done here or on clang's side? 

(I'm using 2.1.1 of this library).

**Comment by nlohmann** [comment] 2017-04-05 08:47
Could this be a duplicate of #512?

**Comment by pboettch** [comment] 2017-04-05 08:54
It is. Sorry for not checking the existing issues.

**Comment by nlohmann** [comment] 2017-04-05 08:55
No problem, thanks for reporting anyway! I unfortunately did not find the time to fix it. I'm using Clang 5 myself, but did not run into this issue myself.

**Closed by nlohmann** 2017-04-05 08:55 UTC

**Comment by nlohmann** [comment] 2017-04-07 14:31
Fixed, see #512.
