### ISSUE TITLE
Implicit assignment to std::string fails

### ISSUE THREAD

**Issue by Cleroth** [nlohmann/json#144] opened 2015-11-02 04:58 UTC
Put simply, when constructing a string, you can pass a basic_json:

    std::string s = o["name"];

However, this does not work:

	std::string s;
	s = o["name"];
	s = o["name"].get<std::string>(); // this works

The following compiler errors pop up:

1>g:\files\smoldy_adventure\src\client\units\unitmgr.cpp(53): error C2593: 'operator =' is ambiguous
1>  g:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(1032): note: could be 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(_Elem)'
1>          with
1>          \[
1>              _Elem=char
1>          ] (compiling source file units\unitmgr.cpp)
1>  g:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(1027): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const _Elem *)'
1>          with
1>          \[
1>              _Elem=char
1>          ] (compiling source file units\unitmgr.cpp)
1>  g:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(1011): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &)' (compiling source file units\unitmgr.cpp)
1>  g:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(972): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::initializer_list<_Elem>)'
1>          with
1>          \[
1>              _Elem=char
1>          ] (compiling source file units\unitmgr.cpp)
1>  g:\program files (x86)\microsoft visual studio 14.0\vc\include\xstring(914): note: or       'std::basic_string<char,std::char_traits<char>,std::allocator<char>> &std::basic_string<char,std::char_traits<char>,std::allocator<char>>::operator =(std::basic_string<char,std::char_traits<char>,std::allocator<char>> &&) noexcept' (compiling source file units\unitmgr.cpp)
1>  g:\files\smoldy_adventure\src\client\units\unitmgr.cpp(53): note: while trying to match the argument list '(std::string, stlx::basic_json<std::map,std::vector,std::string,bool,int64_t,double,std::allocator>)'

**Compiler**: Visual Studio 2015

**Comment by nlohmann** [comment] 2015-11-02 06:30
Thanks for reporting! I'll check the issue soon.

**Comment by nlohmann** [comment] 2015-12-06 15:40
Interestingly, the code works using Clang, but I get an error using GCC.

**Comment by nlohmann** [comment] 2015-12-06 15:42
Unfortunately, I cannot reproduce the error with GCC or Clang. As I have no access to MSVC, I cannot dig deeper into the error. Do you have any idea what the reason could be that MSVC rejects the code?

**Comment by Cleroth** [comment] 2015-12-06 15:48
I couldn't really find the reason. I'll check again in a bit.
Meanwhile, VS 2015 is free, and if you don't want the IDE you can get just the compiler: http://blogs.msdn.com/b/vcblog/archive/2015/11/02/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments.aspx

**Comment by nlohmann** [comment] 2015-12-06 16:15
I am not using a Windows system, so trying MSVC is still difficult :-)

**Comment by ZahlGraf** [comment] 2015-12-06 16:51
I can confirm this issue with MSVC 2015. The workaround with get<std::string>() works well for me.

**Comment by Cleroth** [comment] 2015-12-16 11:12
Why?

**Comment by nlohmann** [comment] 2015-12-16 11:16
I am unable to debug MSVC error messages. If you have any idea how to fix it, I would be happy.

**Comment by Cleroth** [comment] 2015-12-16 12:29
The problem is that basic_json can convert to both a `char` and a `const char *`, so MSVC doesn't know which function to call. The only solution I've found is to prevent implicit conversion to `char` (ie. by adding `typename = std::enable_if<!std::is_same<ValueType, char>::value>::type` to `operator ValueType()`).
You could probably easily replicate this by creating a dummy class with two `operator=` templates, one which takes a `char`, and the other a `const char *`.
I'm curious as to how this even works in GCC/Clang... How are they implementing the `operator=`?

**Comment by Furcube** [comment] 2015-12-19 19:08
GCC 5.3.0 on linux produces similar error. Need to use explicit conversion.

**Comment by Cleroth** [comment] 2015-12-19 19:14
Clang 3.7 also reports the error.

**Comment by nlohmann** [comment] 2015-12-20 14:38
I fixed the code (see https://github.com/nlohmann/json/commit/457bfc2401028a9eb42b738401935d3ad1e1d984) and added test cases. The code compiles for GCC and Clang, but AppVeyor (https://ci.appveyor.com/project/nlohmann/json) fails to compile the code with MSVC. Does anyone have an idea what could be the issue?

**Comment by erichkeane** [comment] 2015-12-30 22:07
@nlohmann : I checked out master with a VM, and get the same issue on Master, so I would say that the issue is NOT with the proposed patch, but with master itself.

**Comment by Cleroth** [comment] 2015-12-30 22:34
The patch is on master, I believe.

**Comment by erichkeane** [comment] 2015-12-30 22:43
@Cleroth: I mean the latest issue that he's having in AppVeyor.  Even without the std::string::operator= stuff, I get the issue of an ambigious operator <<.

I filed bug #167 to comprehend the issue that is blocking this currently.

**Comment by twelsby** [comment] 2016-01-22 14:55
This is fixed in pull #183 - see issue #167.

**Comment by nlohmann** [comment] 2016-01-24 17:39
@twelsby, do I understand correctly that this issue was solved by PR #188?

**Comment by twelsby** [comment] 2016-01-25 23:50
@nlohmann. yes.  Actually it was fixed in 457bfc2 but that created side effects that were fixed in PR #188.  As that pull has now been merged, the current situation on master is that this is fixed.  You should be able to close this issue.

**Comment by nlohmann** [comment] 2016-01-26 05:26
Thanks!

**Closed by nlohmann** 2016-01-26 05:26 UTC
Labels: bug, confirmed, visual studio

**Comment by thomasdullien** [comment] 2016-12-16 07:44
Hey there,

it seems the issue is cropping up for me again. I am trying to compile the same project on GCC and on Clang (built from current trunk), and the unit test compilation is failing for issue 144:

/XXX/project-zero/thomasdullien/XXX/json-src/test/src/unit-regression.cpp:250:12: error: 
      use of overloaded operator '=' is ambiguous (with operand types 'std::string' (aka 'basic_string<char,
      char_traits<char>, allocator<char> >') and 'value_type' (aka 'nlohmann::basic_json<std::map, std::vector,
      std::__1::basic_string<char>, bool, long, unsigned long, double, std::allocator>'))
        s2 = o["name"];
        ~~ ^ ~~~~~~~~~
/usr/local/bin/../include/c++/v1/string:825:19: note: candidate function
    basic_string& operator=(basic_string&& __str)
                  ^
/usr/local/bin/../include/c++/v1/string:820:19: note: candidate function
    basic_string& operator=(const basic_string& __str);
                  ^
/usr/local/bin/../include/c++/v1/string:822:19: note: candidate function
    basic_string& operator=(__self_view __sv)  {return assign(__sv);}
                  ^
1 error generated.
make[2]: *** [json-build/test/CMakeFiles/json_unit.dir/src/unit-regression.cpp.o] Error 1
make[1]: *** [json-build/test/CMakeFiles/json_unit.dir/all] Error 2
make: *** [all] Error 2

What's the best way to help fixing this? :) (btw, big fan of your library)

**Comment by nlohmann** [comment] 2016-12-16 08:18
That is strange, because this regression test is run with every commit on AppVeyor, see https://ci.appveyor.com/project/nlohmann/json/history.

**Comment by jaredgrubb** [comment] 2016-12-16 08:59
Maybe it's a C++17 thing? The "self view" sounds a bit like the new string view.

**Comment by thomasdullien** [comment] 2016-12-16 09:38
Hey there,

so I downgraded to Clang 3.5, and it all works. I think we should not worry
about it for now - it may be a transitory issue
caused by me using trunk clang.

Cheers,
Thomas

2016-12-16 9:59 GMT+01:00 Jared Grubb <notifications@github.com>:
