### ISSUE TITLE
Repository is almost 450MB

### ISSUE THREAD

**Issue by toomanybananas** [nlohmann/json#1497] opened 2019-02-28 18:39 UTC
The size of this repository is 436MB unpacked (although the download is 'only' ~150MB), which is insane for a tiny JSON parsing library. There are multiple cases where (IMO) the size can be trimmed down massively without actually impacting the repo.

The `.git` directory is 178MB, likely since you have a lot of changed binary files. You can easily slash the size of this directory by ~90% using `git repack` (which has drawbacks for repo history, but unless you really care about specific info about changes from years ago this is fine).

Why do you have a 23MB file of 1000000 signed integers in `test/data/regression/signed_ints.json` Do any of those ints besides the first few thousand really contribute any code coverage? I'd wager not. If the purpose of that many is to make sure the program can handle really large JSON files, why is there also another 23MB of unsigned integers? And 22MB of floats? Having lots of tests is good but this is seriously affecting users with slow internet speed who want to contribute to the project.

**Comment by nlohmann** [comment] 2019-02-28 21:23
Duplicate of #96.

**Closed** 2020-05-04 18:58 UTC
Labels: release item: :hammer: further change, solution: duplicate, solution: proposed fix
