### ISSUE TITLE
Confused about iterating through json objects

### ISSUE THREAD

**Issue by DanTheColoradan** [nlohmann/json#49] opened 2015-03-17 22:06 UTC
If I have:

```{.json}
{
  "england": {
    "name": "euro",
    "value": 57.99
  },
  "mexico": {
    "name": "peso",
    "value": 31.99
  },
  "us": {
    "name": "USD",
    "value": 42.99
  }
}
```

And I want to iterate through each, how would I do so?

My attempt so far has been similar to the following:

```{.cpp}
std::ifstream input_file( const string file_path );
nlohmann::json currencies_json;
currencies_json << input_file;
input_file.close();

unordered_map <string, currency_class> currencies;
for ( const auto currency_json: currencies_json ) {
    currency_class new_currency;

    new_currency[ "country" ] = ???
    new_currency[ "name" ] = ???
    new_currency[ "value"] = ???

    currencies[ country ] = new_currency;
}
```

I've tried it a a few ways including - for example - creating a string for `new_currency[ "country" ]` first and then storing it in it like `new_currency[ "country" ] = my_string`, but I get errors such as:

```{.sh}
no member named 'key' in 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, double, std::allocator>'
```

or

```{.sh}
[....]:1073:20: error: 'm_it' is a private member of 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>,
      bool, long long, double, std::allocator>::const_iterator'
           result.m_it.object_iterator = m_value.object->find(key);
                   ^
[...]:89:32: note: in instantiation of member function 'nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, double,
      std::allocator>::find' requested here
                const auto iterator = currencies.find("country");
                                             ^
[...]/build/dependencies/json-prefix/src/json/src/json.hpp:3007:96: note: declared private here
        internal_iterator<typename array_t::const_iterator, typename object_t::const_iterator> m_it;
```

Could you provide some guidance? I'd really appreciate it!

**Comment by DanTheColoradan** [comment] 2015-03-18 00:01
Here is an [extended example](https://gist.github.com/DanTheColoradan/58cc137d39dbf758d2ed).

**Comment by nlohmann** [comment] 2015-03-18 02:13
Dear @DanTheColoradan

Thanks for reporting. I'll check your issue once I'm back from holidays (next week).

All the best
Niels

**Comment by gnzlbg** [comment] 2015-03-20 09:31
Duplicate of #43 .

**Comment by nlohmann** [comment] 2015-03-20 09:32
Thanks! I'll fix it as soon as possible.

**Comment by gnzlbg** [comment] 2015-03-20 09:34
@nlohmann No rush, we have a workaround. Enjoy the holidays :P

**Comment by DanTheColoradan** [comment] 2015-03-20 15:07
Thanks @gnzlbg! And I agree @nlohmann, the workaround is pretty simple so enjoy your vacation :) A new season is upon us.

**Comment by gnzlbg** [comment] 2015-03-24 15:53
This issue should have been closed by https://github.com/nlohmann/json/commit/bb2671df11a33006869212a436766736eb4c4204.

**Comment by nlohmann** [comment] 2015-03-26 17:01
All iterators have now member functions `key()` to retrieve the key for objects and `value()` to retrieve the value. This should fix the mentioned issue.

**Closed by nlohmann** 2015-03-26 17:01 UTC
Labels: bug

**Comment by DanTheColoradan** [comment] 2015-03-26 17:03
Awesome. Thank you!
