### ISSUE TITLE
type must be number, but is null

### ISSUE THREAD

**Issue by tesla-cat** [nlohmann/json#3956] opened 2023-02-24 06:45 UTC
### Description

- my json data contains huge amount of NaNs, instead of parsing it into null and give me this error `type must be number, but is null`, why don't you just parse it into [std::nan](https://en.cppreference.com/w/cpp/numeric/math/nan) ? 
- this will save users from so much trouble!!!

- i know you wrote this https://json.nlohmann.me/features/types/number_handling/#nan-handling
- but this is not user friendly, do i need to write `if(! json_data.is_null()){ float x = json_data;}` manually for every variable that is possibly NaN ?

### Reproduction steps

.

### Expected vs. actual results

.

### Compiler and operating system

.

### Library version

.

### Validation

- [ ] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [ ] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by nlohmann** [comment] 2023-03-05 13:14
Duplicate of #3799.

**Closed as completed** 2023-03-05 13:15 UTC
Labels: solution: duplicate, solution: wontfix
