### ISSUE TITLE
Warning about potential null dereference in GCC 12.1 (Fedora 36)

### ISSUE THREAD

**Issue by timdave13** [nlohmann/json#3525] opened 2022-06-08 18:18 UTC
### Description

Moving from GCC 11 to 12 a warning is emitted about a potential null dereference.  With no code change, just a complier change this warning emerges.

### Reproduction steps

build with GCC 12 using ` g++ main.cpp -O2 -DNDEBUG -Wnull-dereference`

### Expected vs. actual results

Expected no warnings, but got a warning

### Minimal code example

```Shell
#include <nlohmann-json/json.hpp>

#include <string>

// g++ main.cpp -O2 -DNDEBUG -Wnull-dereference
void decode_json_map( nlohmann::json const& tree, std::string const& key )
{
    if( auto map_it = tree.find( key ); map_it != tree.end() )
    {
        for( auto p_it = map_it->begin(), end = map_it->end(); p_it != end; ++p_it )
        {
        }
    }
}

int main()
{
}
```

### Error messages

```Shell
g++ main.cpp -O2 -DNDEBUG -Wnull-dereference
In file included from main.cpp:1:
In constructor ‘nlohmann::detail::iter_impl<BasicJsonType>::iter_impl(pointer) [with BasicJsonType = const nlohmann::basic_json<>]’,
    inlined from ‘nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::const_iterator nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::cend() const [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; BinaryType = std::vector<unsigned char>]’ at /usr/include/nlohmann-json/json.hpp:22294:24,
    inlined from ‘nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::const_iterator nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::end() const [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer; BinaryType = std::vector<unsigned char>]’ at /usr/include/nlohmann-json/json.hpp:22264:21,
    inlined from ‘void decode_json_map(const nlohmann::json&, const std::string&)’ at main.cpp:10:61:
/usr/include/nlohmann-json/json.hpp:11678:27: warning: potential null pointer dereference [-Wnull-dereference]
11678 |         switch (m_object->m_type)
```

### Compiler and operating system

GCC 12.1 on Fedora 36

### Library version

3.9.1

### Validation

- [X] The bug also occurs if the latest version from the [`develop`](https://github.com/nlohmann/json/tree/develop) branch is used.
- [X] I can successfully [compile and run the unit tests](https://github.com/nlohmann/json#execute-unit-tests).

**Comment by falbrechtskirchinger** [comment] 2022-06-08 18:23
Odd. I can't reproduce the issue.

**Comment by timdave13** [comment] 2022-06-08 18:29
Same OS and compiler?

**Comment by falbrechtskirchinger** [comment] 2022-06-08 18:37
Confirmed with:
g++-12.1.1 (Gentoo 12.1.1_p20220604 p7) 12.1.1 20220604
g++-13.0.0 (Gentoo 13.0.0 p, commit b4801c49e6e9607ec0115a71417fbb4e5a4f4967) 13.0.0 20220607 (experimental)
g++ (Compiler-Explorer-Build-gcc--binutils-2.38) 12.1.0
g++ (Compiler-Explorer-Build-gcc-2005b9b888eeac078f2524b1521885f4b5453894-binutils-2.38) 13.0.0 20220607 (experimental)

`-O2 -DNDEBUG` are critical.

**Comment by falbrechtskirchinger** [comment] 2022-06-08 18:46
```cpp
    explicit iter_impl(pointer object) noexcept : m_object(object)
    {
        JSON_ASSERT(m_object != nullptr);

        switch (m_object->m_type)
```

`-DNDEBUG` removes the assert and therefore the `nullptr` check. Following the call stack doesn't reveal anything suspicious either. Looks like a clear false positive to me. There's nothing else to do here. :man_shrugging:

**Comment by timdave13** [comment] 2022-06-08 19:43
I made a change something like `#define JSON_ASSERT( x ) assert( x ); if(!(x)) throw std::runtime_error{"..."}` to make the problem go away but there does seem to be a potential problem hiding there.

**Comment by falbrechtskirchinger** [comment] 2022-06-08 19:57
```
warning: potential null pointer dereference [-Wnull-dereference]
```

"Potential" being the operative word.

I can follow the pointer being passed. As long as `this` (the `basic_json` object on which `begin()` and `end()` are called) isn't a `nullptr`, there's no problem. Also, an actual null dereference would crash the program immediately ... has that happened?

**Comment by nlohmann** [comment] 2022-06-08 20:15
Maybe adding `HEDLEY_NON_NULL(1)` could help, because then the compiler could know that `m_object` cannot be null. Can you try this?

**Comment by nlohmann** [comment] 2022-06-08 20:27
Then I guess we're out of luck and can only suppress this warning for this function via some `HEDLEY_DIAGNOSTIC_PUSH` magic, because otherwise the same issue may come up some time in the future.

**Comment by timdave13** [comment] 2022-06-08 20:56
Not defining NDEBUG is not a good option since it affects the whole program and it is defined by the build system.  #undef before including this header is also not a desirable option.  I would prefer not to modify the source.

**Comment by nlohmann** [comment] 2022-06-09 04:42
I would just annotate that function to not trigger that specific warning.

**Comment by falbrechtskirchinger** [comment] 2022-06-09 04:53
> Then I guess we're out of luck and can only suppress this warning for this function via some `HEDLEY_DIAGNOSTIC_PUSH` magic, because otherwise the same issue may come up some time in the future.

The diagnostic is only issued after some compiler transformation in the constructor of `iter_imp` when called from `end()`. The warning is not given for any other occurrence of the same line of code in any other member function of `iter_impl` it also isn't given when `iter_impl` is constructed from `begin()`.

Building the unit tests with the same flags, I get this diagnostic for standard library headers! (Which smells like a GCC bug since system headers shouldn't emit warnings.)
```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/bits/streambuf_iterator.h:35,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/iterator:66,
                 from /home/flo/projects/json/develop/include/nlohmann/json.hpp:61,
                 from /home/flo/projects/json/develop/tests/src/unit-inspection.cpp:32:
In member function ‘std::basic_streambuf<_CharT, _Traits>::char_type* std::basic_streambuf<_CharT, _Traits>::egptr() const [with _CharT = char; _Traits = std::char_traits<char>]’,
    inlined from ‘std::basic_streambuf<_CharT, _Traits>::int_type std::basic_streambuf<_CharT, _Traits>::sbumpc() [with _CharT = char; _Traits = std::char_traits<char>]’ at /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/streambuf:324:49,
    inlined from ‘std::istreambuf_iterator<_CharT, _Traits>& std::istreambuf_iterator<_CharT, _Traits>::operator++() [with _CharT = char; _Traits = std::char_traits<char>]’ at /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/bits/streambuf_iterator.h:172:17,
    inlined from ‘void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_construct(_InIterator, _InIterator, std::input_iterator_tag) [with _InIterator = std::istreambuf_iterator<char, std::char_traits<char> >; _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ at /usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/bits/basic_string.tcc:178:6:
/usr/lib/gcc/x86_64-pc-linux-gnu/12.1.1/include/g++-v12/streambuf:493:30: warning: potential null pointer dereference [-Wnull-dereference]
  493 |       egptr() const { return _M_in_end; }
      |                              ^~~~~~~~~
```
(And 3 more warnings like this in the same header.)

Also, I should have taken a closer look at your code:
```cpp
void decode_json_map( nlohmann::json const& tree, std::string const& key )
{
    if( auto map_it = tree.find( key ), map_end = tree.end(); map_it != map_end )
    {
        auto &map = *map_it;
        for( auto p_it = map.begin(), end = map.end(); p_it != end; ++p_it )
        {
        }
    }
}
```

This is enough to not trigger the warning, even though I can still cause a null dereference:
```cpp
int main() {
    nlohmann::json *j = nullptr;
    decode_json_map(*j, "key")
}
```
(Of course, I also have to compile without `-O2` or that code will be removed by the compiler.)

```
$ ./a.out
Segmentation fault (core dumped)
```

**Comment by nlohmann** [comment] 2022-06-09 06:25
Then I guess there's nothing to do on our side. I would close the issue unless anyone has a better idea.

**Closed** 2022-06-12 12:32 UTC
Labels: solution: invalid

**Comment by Youda008** [comment] 2025-10-16 13:25
Could you please at least surround that problematic line with
```
#ifdef __GNUC__
 #pragma GCC diagnostic push
 #pragma GCC diagnostic ignored "-Wnull-dereference"
#endif
```
```
#ifdef __GNUC__
 #pragma GCC diagnostic pop
#endif
```

When compiling a larger project, the spam of warnings gets a bit overwhelming.

Compiling with: `gcc version 14.2.0 (Debian 14.2.0-19)`

**Comment by nlohmann** [comment] 2025-10-16 14:58
No, I don't think changing the code to avoid a false positive is a good idea.

**Comment by Youda008** [comment] 2025-10-16 15:08
Why? In contrast with a command line option, you could avoid warning only for that particular line that is known to cause problems. If we supress the warning in our build system, we have to supress it at least for the whole file, possibly the whole library.

**Comment by t-b** [comment] 2025-10-17 23:20
I also agree with @nlohmann that this is not this librarie's business in handling bogus compiler warnings.

In one of my projects where I'm using this library here I'm doing

```cpp
#ifdef MAC
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wpadded"
#pragma clang diagnostic ignored "-Wswitch-enum"
#pragma clang diagnostic ignored "-Wc++17-extensions"
#pragma clang diagnostic ignored "-Wweak-vtables"
#pragma clang diagnostic ignored "-Wcovered-switch-default"
#endif

#include <nlohmann/json.hpp>

using json = nlohmann::json;

#ifdef MAC
#pragma clang diagnostic pop
#endif
```

to silence compiler warnings. IMHO this is the way to go.

**Comment by nlohmann** [comment] 2025-10-18 09:41
@t-b Thanks for sharing!

We test with all warnings enabled (`-Weverything` on Clang and 300+ `-W` flags for GCC) and set the following exclusions.

```
# Ignored Clang warnings:
# -Wno-c++98-compat               The library targets C++11.
# -Wno-c++98-compat-pedantic      The library targets C++11.
# -Wno-deprecated-declarations    The library contains annotations for deprecated functions.
# -Wno-extra-semi-stmt            The library uses assert which triggers this warning.
# -Wno-padded                     We do not care about padding warnings.
# -Wno-covered-switch-default     All switches list all cases and a default case.
# -Wno-unsafe-buffer-usage        Otherwise Doctest would not compile.
# -Wno-missing-noreturn           We found no way to silence this warning otherwise, see PR #4871

# Ignored GCC warnings:
# -Wno-abi-tag           We do not care about ABI tags.
# -Wno-aggregate-return  The library uses aggregate returns.
# -Wno-long-long         The library uses the long long type to interface with system functions.
# -Wno-namespaces        The library uses namespaces.
# -Wno-nrvo              Doctest triggers this warning.
# -Wno-padded            We do not care about padding warnings.
# -Wno-system-headers    We do not care about warnings in system headers.
# -Wno-templates         The library uses templates.
```

See https://json.nlohmann.me/community/quality_assurance/#c-language-compliance-and-compiler-compatibility
